#!/usr/bin/perl
# 99aeabc9ec7fe80b1b39f5e53dc7e49e      <- self-modifying Perl magic

# This is a self-modifying Perl file. I'm sorry you're viewing the source (it's
# really gnarly). If you're curious what it's made of, I recommend reading
# http://github.com/spencertipping/writing-self-modifying-perl.
#
# If you got one of these from someone and don't know what to do with it, send
# it to spencer@spencertipping.com and I'll see if I can figure out what it
# does.

# For the benefit of HTML viewers (this is hack):
# <div id='cover' style='position: absolute; left: 0; top: 0; width: 10000px; height: 10000px; background: white'></div>

$|++;

my %data;
my %transient;
my %externalized_functions;
my %datatypes;

my %locations;          # Maps eval-numbers to attribute names

sub meta::define_form {
  my ($namespace, $delegate) = @_;
  $datatypes{$namespace} = $delegate;
  *{"meta::${namespace}::implementation"} = $delegate;
  *{"meta::$namespace"} = sub {
    my ($name, $value, %options) = @_;
    chomp $value;
    $data{"${namespace}::$name"} = $value unless $options{no_binding};
    &$delegate($name, $value) unless $options{no_delegate}}}

sub meta::eval_in {
  my ($what, $where) = @_;

  # Obtain next eval-number and alias it to the designated location
  @locations{eval('__FILE__') =~ /\(eval (\d+)\)/} = ($where);

  my $result = eval $what;
  $@ =~ s/\(eval \d+\)/$where/ if $@;
  warn $@ if $@;
  $result}

meta::define_form 'meta', sub {
  my ($name, $value) = @_;
  meta::eval_in($value, "meta::$name")};

meta::meta('configure', <<'__');
# A function to configure transients. Transients can be used to store any number of
# different things, but one of the more common usages is type descriptors.

sub meta::configure {
  my ($datatype, %options) = @_;
  $transient{$_}{$datatype} = $options{$_} for keys %options;
}
__
meta::meta('externalize', <<'__');
# Function externalization. Data types should call this method when defining a function
# that has an external interface.

sub meta::externalize {
  my ($name, $attribute, $implementation) = @_;
  my $escaped = $name;
  $escaped =~ s/[^A-Za-z0-9:]/_/go;
  $externalized_functions{$name} = $externalized_functions{$escaped} = $attribute;
  *{"::$name"} = *{"::$escaped"} = $implementation || $attribute;
}

__
meta::meta('functor::editable', <<'__');
# An editable type. This creates a type whose default action is to open an editor
# on whichever value is mentioned. This can be changed using different flags.

sub meta::functor::editable {
  my ($typename, %options) = @_;

  meta::configure $typename, %options;
  meta::define_form $typename, sub {
    my ($name, $value) = @_;

    $options{on_bind} && &{$options{on_bind}}($name, $value);

    meta::externalize $options{prefix} . $name, "${typename}::$name", sub {
      my $attribute             = "${typename}::$name";
      my ($command, @new_value) = @_;

      return &{$options{default}}(retrieve($attribute)) if ref $options{default} eq 'CODE' and not defined $command;
      return edit($attribute) if $command eq 'edit' or $options{default} eq 'edit' and not defined $command;
      return associate($attribute, @new_value ? join(' ', @new_value) : join('', <STDIN>)) if $command eq '=' or $command eq 'import' or $options{default} eq 'import' and not defined $command;
      return retrieve($attribute)}}}
__
meta::meta('functor::html-templates', <<'__');
my @html_elements = qw/html head title meta script style link body div/;    # Very incomplete list

for my $e (@html_elements) {
  meta::externalize "template::$e", "template::$e", sub {
    my ($line, $block) = @_;
    "<$e $line>\n$block\n</$e>";
  };
}

__
meta::meta('type::alias', <<'__');
meta::configure 'alias', inherit => 0;
meta::define_form 'alias', sub {
  my ($name, $value) = @_;
  meta::externalize $name, "alias::$name", sub {
    # Can't pre-tokenize because shell::tokenize doesn't exist until the library::
    # namespace has been evaluated (which will be after alias::).
    shell::run(shell::tokenize($value), shell::tokenize(@_));
  };
};
__
meta::meta('type::bootstrap', <<'__');
# Bootstrap attributes don't get executed. The reason for this is that because
# they are serialized directly into the header of the file (and later duplicated
# as regular data attributes), they will have already been executed when the
# file is loaded.

meta::configure 'bootstrap', extension => '.pl', inherit => 1;
meta::define_form 'bootstrap', sub {};
__
meta::meta('type::bzip2', <<'__');
meta::configure 'bzip2', inherit => 1;
meta::define_form 'bzip2', sub {
  my ($name, $value) = @_;

  meta::externalize $name, "bzip2::$name", sub {
    my ($command, @arguments) = @_;
    return terminal::error("temporary uncompressed attribute $name already exists") if exists $data{$name};

    uncompress($name);
    my $result = dangerous('', sub {&$command($name, @arguments)});
    compress($name);

    $result;
  };
};

__
meta::meta('type::cache', <<'__');
meta::configure 'cache', inherit => 0;
meta::define_form 'cache', \&meta::bootstrap::implementation;
__
meta::meta('type::cached_dependency', <<'__');
meta::configure 'cached_dependency', inherit => 0, extension => '';
meta::define_form 'cached_dependency', \&meta::bootstrap::implementation;
__
meta::meta('type::configuration', <<'__');
meta::functor::editable 'configuration', inherit => 0, extension => '.conf', default => sub {
  # Any lines starting with #, with or without leading whitespace, are treated as comments.
  # Comments are not parsed in option text; that is, you could specify an option that contained
  # a # and the # and following text would be considered part of that option.
  my ($data) = @_;
  my @options = grep /:\h+/o && ! /^\h*#/o && ! /^\h*$/o, split(/\v+/o, $data);
  s/^\h+//o for @options;
  my @key_values = map split(/\h*:\h+/o, $_, 2), @options;
  $key_values[$_ << 1] and $key_values[$_ << 1] =~ s/\s/_/go for 0 .. @key_values >> 1;
  $key_values[$_ << 1] and $key_values[$_ << 1] = lc $key_values[$_ << 1] for 0 .. @key_values >> 1;
  @key_values;
};

__
meta::meta('type::data', 'meta::functor::editable \'data\', extension => \'\', inherit => 0, default => \'cat\';');
meta::meta('type::function', <<'__');
meta::configure 'function', extension => '.pl', inherit => 1;
meta::define_form 'function', sub {
  my ($name, $value) = @_;
  meta::externalize $name, "function::$name", meta::eval_in("sub {\n$value\n}", "function::$name");
};
__
meta::meta('type::hook', <<'__');
meta::configure 'hook', extension => '.pl', inherit => 0;
meta::define_form 'hook', sub {
  my ($name, $value) = @_;
  *{"hook::$name"} = meta::eval_in("sub {\n$value\n}", "hook::$name");
};
__
meta::meta('type::inc', <<'__');
meta::configure 'inc', inherit => 1, extension => '.pl';
meta::define_form 'inc', sub {
  use File::Path 'mkpath';
  use File::Basename qw/basename dirname/;

  my ($name, $value) = @_;
  my $tmpdir   = basename($0) . '-' . $$;
  my $filename = "/tmp/$tmpdir/$name";

  push @INC, "/tmp/$tmpdir" unless grep /^\/tmp\/$tmpdir$/, @INC;

  mkpath(dirname($filename));
  unless (-e $filename) {
    open my $fh, '>', $filename;
    print $fh $value;
    close $fh;
  }
};
__
meta::meta('type::indicator', <<'__');
# Shell indicator function. The output of each of these is automatically
# appended to the shell prompt.

meta::configure 'indicator', inherit => 1, extension => '.pl';
meta::define_form 'indicator', sub {
  my ($name, $value) = @_;
  *{"indicator::$name"} = meta::eval_in("sub {\n$value\n}", "indicator::$name");
};
__
meta::meta('type::internal_function', <<'__');
meta::configure 'internal_function', extension => '.pl', inherit => 1;
meta::define_form 'internal_function', sub {
  my ($name, $value) = @_;
  *{$name} = meta::eval_in("sub {\n$value\n}", "internal_function::$name");
};
__
meta::meta('type::js', <<'__');
meta::functor::editable 'js', extension => '.js', inherit => 1;

__
meta::meta('type::library', <<'__');
meta::configure 'library', extension => '.pl', inherit => 1;
meta::define_form 'library', sub {
  my ($name, $value) = @_;
  meta::eval_in($value, "library::$name");
};
__
meta::meta('type::message_color', <<'__');
meta::configure 'message_color', extension => '', inherit => 1;
meta::define_form 'message_color', sub {
  my ($name, $value) = @_;
  terminal::color($name, $value);
};
__
meta::meta('type::meta', <<'__');
# This doesn't define a new type. It customizes the existing 'meta' type
# defined in bootstrap::initialization. Note that horrible things will
# happen if you redefine it using the editable functor.

meta::configure 'meta', extension => '.pl', inherit => 1;
__
meta::meta('type::module', <<'__');
meta::functor::editable 'module', extension => '.js.sdoc', inherit => 1, default => 'edit';

__
meta::meta('type::parent', <<'__');
meta::define_form 'parent', \&meta::bootstrap::implementation;
meta::configure 'parent', extension => '', inherit => 1;
__
meta::meta('type::retriever', <<'__');
meta::configure 'retriever', extension => '.pl', inherit => 1;
meta::define_form 'retriever', sub {
  my ($name, $value) = @_;
  $transient{retrievers}{$name} = meta::eval_in("sub {\n$value\n}", "retriever::$name");
};
__
meta::meta('type::sdoc', <<'__');
# A meta-type for other types. So retrieve('js::main') will work if you have
# the attribute 'sdoc::js::main'. The filename will be main.js.sdoc.

meta::functor::editable 'sdoc', inherit => 1, extension => sub {
  extension_for(attribute($_[0])) . '.sdoc';
};
__
meta::meta('type::slibrary', <<'__');
meta::configure 'slibrary', extension => '.pl.sdoc', inherit => 1;
meta::define_form 'slibrary', sub {
  my ($name, $value) = @_;
  meta::eval_in(sdoc("slibrary::$name"), "slibrary::$name");
};

__
meta::meta('type::state', <<'__');
# Allows temporary or long-term storage of states. Nothing particularly insightful
# is done about compression, so storing alternative states will cause a large
# increase in size. Also, states don't contain other states -- otherwise the size
# increase would be exponential.

# States are created with the save-state function.

meta::configure 'state', inherit => 0, extension => '.pl';
meta::define_form 'state', \&meta::bootstrap::implementation;
__
meta::meta('type::template', <<'__');
meta::configure 'template', extension => '.pl', inherit => 1;
meta::define_form 'template', sub {
  my ($name, $value) = @_;
  meta::externalize "template::$name", "template::$name", meta::eval_in("sub {\n$value\n}", "template::$name");
};
__
meta::alias('ed', 'edit sdoc::js::dependencies');
meta::alias('em', 'edit sdoc::js::modules');
meta::alias('er', <<'__');
edit sdoc::js::repl -f

__
meta::alias('et', <<'__');
edit sdoc::js::test -f

__
meta::alias('scratch', <<'__');
edit sdoc::js::scratch -f

__
meta::bootstrap('html', <<'__');
<html>
  <head>
  <meta http-equiv='content-type' content='text/html; charset=UTF-8' />
  <link rel='stylesheet' href='http://spencertipping.com/perl-objects/web/style.css'/>

  <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js'></script>
  <script src='http://spencertipping.com/caterwaul/caterwaul.all.min.js'></script>
  <script src='http://spencertipping.com/montenegro/montenegro.client.js'></script>
  <script src='http://spencertipping.com/perl-objects/web/attribute-parser.js'></script>
  <script src='http://spencertipping.com/perl-objects/web/interface.js'></script>
  </head>
  <body></body>
</html>

__
meta::bootstrap('initialization', <<'__');
#!/usr/bin/perl
# 99aeabc9ec7fe80b1b39f5e53dc7e49e      <- self-modifying Perl magic

# This is a self-modifying Perl file. I'm sorry you're viewing the source (it's
# really gnarly). If you're curious what it's made of, I recommend reading
# http://github.com/spencertipping/writing-self-modifying-perl.
#
# If you got one of these from someone and don't know what to do with it, send
# it to spencer@spencertipping.com and I'll see if I can figure out what it
# does.

# For the benefit of HTML viewers (this is hack):
# <div id='cover' style='position: absolute; left: 0; top: 0; width: 10000px; height: 10000px; background: white'></div>

$|++;

my %data;
my %transient;
my %externalized_functions;
my %datatypes;

my %locations;          # Maps eval-numbers to attribute names

sub meta::define_form {
  my ($namespace, $delegate) = @_;
  $datatypes{$namespace} = $delegate;
  *{"meta::${namespace}::implementation"} = $delegate;
  *{"meta::$namespace"} = sub {
    my ($name, $value, %options) = @_;
    chomp $value;
    $data{"${namespace}::$name"} = $value unless $options{no_binding};
    &$delegate($name, $value) unless $options{no_delegate}}}

sub meta::eval_in {
  my ($what, $where) = @_;

  # Obtain next eval-number and alias it to the designated location
  @locations{eval('__FILE__') =~ /\(eval (\d+)\)/} = ($where);

  my $result = eval $what;
  $@ =~ s/\(eval \d+\)/$where/ if $@;
  warn $@ if $@;
  $result}

meta::define_form 'meta', sub {
  my ($name, $value) = @_;
  meta::eval_in($value, "meta::$name")};

__
meta::bootstrap('perldoc', <<'__');
=head1 Self-modifying Perl script

=head2 Original implementation by Spencer Tipping L<http://spencertipping.com>

The prototype for this script is licensed under the terms of the MIT source code license.
However, this script in particular may be under different licensing terms. To find out how
this script is licensed, please contact whoever sent it to you. Alternatively, you may
run it with the 'license' argument if they have specified a license that way.

You should not edit this file directly. For information about how it was constructed, go
to L<http://spencertipping.com/writing-self-modifying-perl>. For quick usage guidelines,
run this script with the 'usage' argument.

=cut

__
meta::bzip2('caterwaul.min.js', <<'__');
M0EIH,3%!62936:.<R1H``U=?@&H`=____[____^_____8!J>^??9??%[=[VS
M;-70ZGFT[UJ>W7<AN^^TNV[GR/5[>>]O=WJ^];QXB]BA1'NSOFQ#8Z:Y5*BB
MM:%-LI1T94B/MW/OAII$"::5/\$TT)M-&@TIZ:333*;0T3Q$\DR>DQ/1I/*&
M#32:!&C03)!I3/2GJ9,GI,CU,AD`\D`T`Q-,$&F02!-1J,!J,RIZF@]0Q-&T
MU&@T>B:9`]$R`:`DU$0(FA&1H&IDS4FILD\B>H9`!Z1M0```T$4DQ*:9J93T
M1IM0TP(#30`&F@T#1H&0:#)H)$B:!-,FB-)Z:&J>F!#4CPD\0U`-'J-IJ:/4
MT-`,W_.8$.5R:@[YPEWQXI9&H\A`>OG^T^5N',LM#/-'BBQ._H4F&<POPZ%(
M+D^'DN\Q>5!"S\+/C@47SIIIA6F%>/\BA]V80=O)R=A<C\=]<,8Q@9#BUP,(
MR1D&#"BB%2@22H,0&"""00"Q!*XSZS7I(MG<A<VOUM&Z+Z%@Z]DQ@,`I@1M<
MAG^$?\/9,_R9K.E:OSXLE-;]/5MGPX0<@Q6`LB!!8-,<F@(A6G:.IW.3Y@*=
M-"DC'5!GEM2#"S]0H#L@^SN@A/K*8]KESB+!N5NSU<S<(JUN)W(#C2\CH/`%
MB'`7UGVGO(RI="X61(C#VP>#92S7N&'%3F=B]6O_[SC:UCFN'6O37(_-7F:S
M`8H;\/B[I7I/.\GWIP8S@`Q!E4E_RQ/OO;WD>QP3\=%EYHQ-BX6X>/3!@3!%
M1<GG0YZN"KDW.L>4@C<0L%.R_ET5:ZU:XX-6-;^AUS_)'/-7NFF$IF)#""12
M=E+:6ZTTX;.??6M54%,"44@:Q[4NM*(YIJY)."EW8W=OL]EEPQ;:F<6692CE
M6+JF-5FB@21D>,\^+B8_C*MNMETTZ76:LVZ2VC5OKK360EJ!&%1/Y3X.K3M\
M!:^`G@>DQ`86V*I]QVH<0O<_\K,#;SN],_G'5NBQZ)W2WSCVW14?AL0*>P(2
M2/3RG![],KH76P.X,\/+SN10+N8+%[G1R4/5@CH\WG<P*O<I##+PK/*9R;%\
M1R<=0Z_W3G:9R'"I,U0^O&&#!GJG(%7871.UBXY)>;U\\E9"+6+YWA:Q!,D:
MY(WPW"66.Q_7QPOKF5NSS\Y#IS6;2RDD[)3^0_TF(P&PH]A2IE0TT)W=%12J
M>>[8/-_"H+JJ!O^J/$,A!>4K1)E$)``6@$<TFY;!%#`.SW;<UP;VLT,,K,2S
M9A(-CETWEEI%8V</7&6@R>BUB556C63JJ'1D$ZYF<"*F*B3`R*!A9MW1X],6
M:TM5X8$B!AU>XQMU[<36^:7"F(>%ZZ+'3!C"D@U`_+WZ.$N.]H9;O$*+DJ'1
M?7(B=`G5';=SL`;6;-)C&G@&2/FHKBFTY.[_WBO-XV<LCR2Y-]I`)*&='O"C
M!7$;X[;]V(L>B(!9!-`PBI)`R^Q=_:UWC8P$[YXGG8W$(YUIC[PPCQ]D_U??
MNPQ5\X`J!E>H!49VB>3@T\NG.QMJRT>S#E51&4LX#45!)B(#_%WPM"350-F/
M[\?]^C++.V4V=H^D<]NL>[&`KNHWHFH-Z@1(<JDF:A5V>M@SZX-@@&R3IL;+
M7N/FN]R3Z:K'C+X@BI07(&5;G%'N*LHO"W$:>:U)X>Q9N!0APY2U#5SO7M;^
MZXZ^I]ZVTAUZ#[D7&./7&YI-,\O>VKU6U4F7&"R!=E&\C;Q7[EGONVBWG5'V
MB)L54Y'/V0/.0^8&PMM]*B<Q<-Y:W<D2DM]]XO`5TA(<'2]H%=:_&2\7A8!=
MR_B<(BM'"T-;ZINFJ,6<B>EP[\7530>.GB8,,%^C'&-=L$N@K?;TY-QB@S*4
M5M4A;%7LQ+?71B&1.C=?R\^K'9T-393HJ@O#*W;ZGW#,ZJOC5-^3:#E$LW7(
M*Q9M\'U7!S.#CY:O+JXUP&<B^5H,B7(%$G06>8,I]"R<3=.Q8Q[&`B>OP#W,
MVB*$05@2][G#FK'V8>2,C-L6P5=E:K?-:,K!F^<2U/3Y&\D5`M!$-$'8`(%(
M#]B--X\4)B`0`+;J$GMYBG0Q$]O4QC4`'[$0XY!AN@1`7U8*];7Z-9S.G`A(
M"H9]4KSNZ%1<[0'I;'W,AMC&$D8>,OCL<KF*VE$)0D!*WF#DW*`*,RZH[>1Q
MSQ876OO;,NC9U48QC2F30`5=`;:=(_67IZ/ZA\8I>'"W,04=ZN`)'I*@@XA\
MV57[W'K(1IKY.^5DL<,R3)'&Q+MCV3]&"=P.8&1GQYVAQ&XJ$#XK-]4?`3@K
MIU6@'%@YH1G'OZY"QX/%Z?KW/_0I;?CJ,`CLL6X8O;2+?-P;11H_EG*Q\G+]
M*WF]J_4VD]6MB/7BI'Z:J(A/[4A0F*_"RGZD!00*%5"4G-Q;XDMS7L3:!BJU
MYAGFLD"("_(&-52,V]!+\YP]!$-M#B/5*3;&O3[$1[/A@+>PWQV<V0SP`?';
M&$OAHT@<T<C/1184Z"*@)E6,$%BAB6V39,[GZ];A[-KQ\"U@)`6$7JD::F7J
M11F$:_G?W4ZD<)H+@R;HT/'0YZ8-"=?7UX,;E5NF4(L.I)[4MRPIDT&$T>5U
MLASY9^^8QZ,:],WDHU8%$V9&B_4BTZE&1B`HNB99WO`SOL[OAG!(C2QUQEVQ
M"P>"5U[21E!6!21P(?!20,:K0W`+9!&&0`E;=*`U<!)V=EN4,;`,K;+!!7,H
M:K76T%2!)[@C@XHH(P62\4N\\91D+Q=8H@SLW7HB"[4!XT.H62**2)*"H`0T
MOTWKJ.7#)`VX&$-[<Z9![B=J[1X?UIP,3HO*RX&LK^SO)>]P>&![Y+^W^R!$
MH8A=-#5X:K:G\L;$L?P%,'>GF]S/:;T@JLPJ^^IRDS9W72M9X&3"-Z9>B'2_
M'PAKGBR(%G!88LM`GT,"/)^ZX&%/Z*;+6[#&U%?R1;^-(_@'13"6HZ>4VMM+
M@U*IK+TS04GV]L=YYUA9#[^2<+Y8#F(L&)[9QM27@7;[I;]IZDX43M5;"H")
ML)%E:GNMHLOCM6/?MT8QAE..23/A1<0B[^-;-^O9/3BW[K9%_HIL/B;R";-.
MT^"VJ,#FDHO@AK+(-6Z&#HZE]_G?].]ZTE'N?4E#WE2#I7#<J280RTN.)$10
M2-ZMA?QVRZPVD.4P1>1R0I(U;:+N+0P<A(H!7<8W>"PD2:4@RK\GRWB)-:%:
MN,.B%"VS_"T7ZP9^(;(8L1&UY0\`2WCSQZGF+,)O?O6,5L;.IP,?:4L+H125
M15]E0+2J6D(@ZB,!3ZX_DS!V_+9-6Z/O][`&B&/.A02ABFQM^A`[I#J9FRB\
M_6K'F.M[ZQ8Q+`4)0@H$)!9`N=GX_>E?94^DNA8J(X^R[5?KG3]U-?1OZZNX
M-Z<8W#7U:YUE>K;PR]<[$4!2119Z&P["-YJS$?C\?BB?F<U<_T_[IA1.['.6
M?1FR#6P7L7VC;W/45`=U72>/CS93DL'2&;K5IM.9S1<X>+#_&.5)\8,/5BMW
MY9N6[!SZ>]_OKAUS,LY=F]DZM?OAQ$XU5=FZ`,:L06(F>.F2XXCD#XL:^&WW
M8"?@N7CJQ&,)^U4&8XJUC=J1%FR;1H,:M.WCL&FIGR0739;IO"P8!)B*XSX3
M<+*N"G@IIJV=8BS[I'?7+/&NW"!Y-'%S]KK$ZYL%<^SL3HX`=CX;@G:8FJ!>
MH$X<8Y49%H<;/+X8W;C!<4_<>U-'"4"DF;S,^BJ94F#!C7Q8/7Q!1S`)1[?5
M>R+..ONB;@%Q+'F(T8/YG>SASW]F5]WDR.1/NXZHG#!^8.KE]JQUZ.0U#`A"
M0$%!.$(!"D=U@M+>#?)2)I7:9\>ZWP"M^"WPMTYP3D&XWF1APGB>?/7>-$-&
M'[P@7&$MAY"6(7]A0^8L`YZ1SU!A'[`61\@R"#GZ14,<XX"U?@(IX!M%L]O6
M**3(2L.R:I))L3])\V\3)P;9%@,(!29ZQB\`,O&0%!.:AT?L&D1[R[WX5(;D
M,OX"3EN#BS^`2D_2:FERE6"28_24!'*@!TSX4_<U65>TO+^6ZU_88-SH]//+
M2P"D%`+](>^(B(('LO]Y\/+;\&,'[CW*%X9$?X!\)2ZY:.R'+!M;P9/-1%O9
M=7011BD$"78CA%H(TYIG$@[LB;21CXE3K??'PNB>&_$-3H])&C1MT+8!Z#X.
M+_I&N-2].Q+=J*<&X#Q>P]/<[+J3\7@[X\O(LPJGGG="YST*!7/Q'8N/I-F0
MHLYXOI%=DB):\YV'/UV2N^-VW055-@VAD.&WPOY-'.RQSF,=9]75;1M>59+5
M04ALX1:IJWJY)::YRE?C5KL8[H7X2/6&:BOEWU<`(#;_73\)=@<U@<)!9<57
M6=@^;5(3]2%*/,_)M8HH1+/BAK\*J?CQ4L]UB-$?RD_QEPS"*_<'!P]>=I>*
MO1&NDVHQ.9*F`SSCL;?([[Y9.&6:=O*+/4@=K!8T5(#\W^UDDYNA#5XN^+,"
M$$+H"I3?WC+>*JU6H.#MM1`P@F`1+_:>HU(34D*O>5@'IC?Z':PR\V>&598.
M!:!<E`(HX*GJ*IS)EW<'$.,I39ER@<WBT"]ZOTO8XHVVZ$E7!!UXVXWTG#J;
MT!]^!:D8*+U<&AO,I9L32;:0-$P%7;6K,3HDQG!5451G:^,6S)NF;%92P:[>
MTW:9]YC!KH;J.C<M^HO)]60MOGC`;C9AR9AFJ82?25J@!$X`JDXB`BZ=ZAB$
M_/'K$O&'WI'H08;-[Q:T#8XEW=CBJ8I;J?%*R3IZ^PV^8=-]&J@Q/<RV"#(L
M6$4!7U^[4LQ(;JCMP%RFCVWG.AIQOM*Z<SYI"PWS.>M2TW:-ZH4%4&1\K;*,
MP#:!]&?<=DZ=;T-ACC"1I>MX3IDBC-J^3.\JC%[47;"F,8&F.]G>8.6,VS#.
M0/([PK8VF]**AL6-2XMFAG.M5O7??=FC2Y)F;;)NSSC1XE&PV+$LE%[I2IT%
M$1@N8P-F84KJQ@LX87Y&W2S13)QR0MN6&"46)C*H5UI5$D[YW.4%<HT+E1T@
M=*-&NFH<(`KV>>RAC,XL4F4PDHX5*Y0HR=2S"UK!&^JKQ3ASKA`Q1E]L"!I+
MD$(ING*MK,=U%S7T5+,,YZ%:54JRRCU0%)3HZI:%NS&IJJ@L%G4!O2O6+UVX
M#(<#;L%>+@V3Z0KPPH9R)CG:0AC6,O%GR4ULV:A%MS)LMN#L20C!+Q-X_S)(
M^YKP6WF%0+\7LRQY74%Y&..(Z43F8;8#6V6K)-Q%I'C"8!_!8L;VDYF$U3*!
M#ORB*4EU+DET!+XS@`;E`E"-<H79K/3?;>-^[KK/,*KU!/J)KR+H1+J=[C+]
MU8>5LJ%#"]56B(LJ3+!+S(ZBOB*UAP(4!+9*IZ,EH.Q6P@ZPJI5`?$[R&!C`
M>OL20V)M+OBN++NBG,G8(SG9#@Q#E[!EW`B&-1T)XD@J+262)V9<'-K4K6ET
MJ3-50B(:,854PPJ$RX0S>-E8JC5>:6#-%5P]#"9F1>)HQV;=BRD/O:XIX@A0
MEW1357:ROHY^;OQ)43>LNC_IF\`%(%8LR-&TPSW-`A]58"B5MINYZ:Z7,:5Q
MG)W47KSVT<G.$[7!?.5X1KQ+E=#PC*ZN+!AY/`56EAG0#`8P&4:@%QACSH`Y
M,+`K%:!(W7(0N(52E?J2+>(M&-IIT`&<RY77EA6*1V%W&A*K/<5DDK=FD;U6
MXE`)"))2`$%2$I>7#5FN:XN/MR0!5RPTVBBV#;$<L'/N@U(5-&#HP"P:=LXK
M8NODE-+;&EBX8CENGC!*S3Y=Q\)^MJ2V2D64D9\\Y::I.KCL\I:F6K82.)15
MT52A46-+02D6@Q4MMJ-8JE`LI*2A?IQ<P+TA&:,<5I]NEY0>9,>9W)14J)=Q
MG>R+6BT-PR&;>.)1#:SN1I;'MFOD>;;3)M<"3<@GXIZ5'W-(-`4*D%(R-0Z)
MR9$8552%LPU4J`=6*)<ALL(WRC@O]$V%#*55:%ZI$K@`G?=9--M@TY<NWNT4
M\X>Q?:_KN%)+2>U6+;"DE#.G69C`.YIFR\2R1@'<DQ9]O$`1W0!&B"32XZ@@
MXE1;2\"P.,&"$%@Q5B[\D($N0.!!8+K12JJOGJG/(TA'VG="/W<NT*D`68\S
MO%K["$27,.\A.N75JJ\Q/I-%K:H0)5$Q,5+EIZ#;N.F(&VNW+>ES3,2_8$YS
M%]@;@1D:F#:$VF<L1E-%VBU))M"/+XQ%.5%MIQ+49:D`9#$F@TP$7F*L%J+%
M@BM`T`)JP+,]@<0>,R2?MCVMQL.WVZM`Z-U1*+D4&(QXJIZ!,NO.>`TF=1VX
M*0T#8A-R#&"K`1%),X+L(2[&DOZZ?*IH:3,&]1A"5K00%($:$2DD)E"26#8C
M@J2=;(!;/$R5-Q#$V#4.R4SRS)E0$P0@@!BCX4"&351`JC<&_#RD!UI]%Y<X
M+&JFDU`AP,.(0B!<XSGM,F`0$A-`,-'@0JA09#`<]Y.Z;LSD-LNK"'D"?.Q2
M$!9).]`J$82=WHGE&*_=W@'/V"KQ$K$=:.H$8HKQK4(U`7L`@=[+.AFB0+^`
M?R?/.TFAN77,$\Y%E,C%"%:.E1HLUA<Y=.'$=.0`V0KGPDH`11@1\<Y,2$PP
M&)ZJ*A+Y>F8`]I#,6\T@P`J%<!QJP%V5(MM8YU7%J%807G18EZ";&QKB0F^Y
M3`DU420+2=/S5@8',9`#5(,^2_"]R#@Z'L2NJBFV'?9%F6A,LA#3$(LE((A*
M%9$!B,EW-.^K-<RY.E&I>;(MB$G1@<DQF5GT3!.1PE51\16%VX*Q:9VF)I2@
MM4*:;0^NTH=\DO(Y0RJ:)5*R@4IA*:BGY6EM"(A0P"DBR#2<'E@4MDY<H1A)
MS`BB:0W.`C"`(73T7)]3."B];I#G>@,,&'[MC*!M>\@U"2&E*`8G$!D^&E7R
MZ^,\9;T*L%VM7/>U8@I"25&0AO6];X*?#?4O09`-8EC):1BH8:058"ER^J&(
M'PC%&<0FB"(&V<-BU(%?4D!3<"5]%<5A6Z3@.@(&I=P.#WAN)$+@37;F8ED/
M,>/CJ3`98<H3E\NE/<N]7GU0E(;E5,(R5($V<[)%1+7,`Q:*4CQL71SB@$(Q
M+BZM!!#$V8HHL[R#X!6+D[0*-#0/5))E*9`0[#U].L5I@*I[_08$3%?1FI(F
M`5!!$/*IEQ@3\S$$%GVV;!I]D,V>S]G._>PLDB2'1@(8.";Q'00)OQ5UKZ6&
MBHQFXN(&+FY:X;YFH8-,PUBS=`U9FC7BC.*TXU,):BWWDJ;3M[>Y0]('<R$`
M8+X3TP.6U&#,`00/A)X!C34GX&&(Q@@QBR*0O$9"R&,88J1Q\N*3:TAPQ-8`
M@O/F*S4EBL,$7M8&@((8V0P/M.F)S%FQ-]&"%A(3>,^`R,$4I"GXZ2=>0E/^
M2/K(<^R'C``^]B!#Q4EN;,H6S4($&`),M6"SMB39#N8<</FJBG3P]GY#QDI!
MBP&",16$MM*NAN^9DVFY/%.^&8?B/8$\\6(!\<Z^AH6MHY4K0P,<D-MO*,C>
M%%206^T\\EZC0LN6PDD6-3.R-K#:$T'H/LU\HQIG-"*R&`W<R&KABJ%F`3`+
M>LG4JWWYP.,$`=&/%JH?YI[_JTRN"!T9`4#[F=3#.2I(90I*%!@*,@Q$2Z,"
M22V$@LBB).:0IBPRR0K2@^O4%S7ZL$SS,!S0E`=7;UM\M^EB!`'A<U7%)N\A
MYRP'I*C:.UF-C3\<]7"\,.%A9"(0W7PQ\@JONI*MWR(]M#[9JP?U4CL_5ZIS
M"S'X.(?0[G2E>`26GN^;;AKLS=4$XEB@$S0+\GGQ?1G!,1_\:04+WV*M]UW;
M#'#1E^WJ\.[&F[3FI6V&_XJ:H\R5#(VU]-G=ID)E.:=&=7NH/.\S&BKCY[F#
M(:JYW%*K[<;?:P2R:[+5<A)()!F2>B"P@9SOX\%7=TI%8=?;=S_B[DBG"A(4
$<YDC0```

__
meta::bzip2('caterwaul.std.min.js', <<'__');
M0EIH,3%!629361GHPDX`!"G_@'5P*$)___`?X@#8#[____]@&[[WN]=7'W-<
MM;EM>=@F:(-5I.]KM[K[WWOC.KIK0/M?;PW>XIY]?.^[.][WWSE]=:77M=T]
M[7;W:1T>4^WGV;?:VI[[[I[V.]@\@ZF7"4T0@GH31DF)H:323])C(H,@]30:
M&@]1H,0(2GB)FBF4T]&2>FD``,@T```)"1&HT$Q2;4]3U/4V4;4QHAIDT:``
M--`"34@@0B&J?Z2GIC5!ZCRC;*@'J!D-`!B")*),C:$33Q&)J,C3$:``#0T`
MR`(DB",30)$\@F:J?JG^J?JCU&C1&3U#0!@!=X?[0R9X"#EXE)-)`/KE/)27
MSCY.3JZ7J4?Q#2%T6'T!,0.?C]G;N>6<W6I1]_$E,L):H4#?XLB;1<SBYDDL
M:[VT-IR$OR-/U+>T+F9^6YYP&AN8#U2*_\^NPQ8;\KQ]G."F`?L"2*`UBKD$
M1_?*PD7&FEB+@#C/Z?J,/!!6CGM<D.B-;UM$U9T+^WO)LG-0-YEQ=)B<Z0_#
MLQNG,:$DJ21A>T$:05;@AK!D$0O<H)7A`?PAGZ=[_=7\>LJ[&\O&"&D8CL00
MRJFD9)IPS)"*M'1CF;'`8-"&:_V'6#"C2]0]4+`37PI<4W2LA@=Y[D*B$8..
M_1[+47-I4;8]4!011!ZRY*R9=:%AKBP",H/6:&#.P])-@XAW6CR).SH[US3$
MQ-^5C;KO0:XA/1&(YD5+4!!J^.?V2S8?.`F&/'Z7/">O^FF/U/I^?P<*-ECW
M-W6?G_&:L`L!`%17W%^65A[B$;I'^<.SPG:0]/-P7O\>=5X1=]5;;>.DKTZ3
MR>B,;^E"FAMLJ'^^VWQM6+Z48T;4-^PY5MJ7*_"KY9\>>::?A@$`R`T]/'UV
M8O7-9CHL/L.1L,M^'SD!U6'IQ7JO/JV]MIW(>3R;%G@P%$Q$@(PB("B,(,2`
MR*1M32A*L%46J,[Q]O#\19T/%#%AYPRMO]]`-9%L/-D\GD.E#0,4>[*!6H%$
M55D.D[T)%&RS977Z('<),3;JB,?D\+T-!R4NR(5HS$L$?^/.SJW5T0[>U.R%
MCF7I!GUE2S:TH+X)+C"%J/!)8;J5"JS5C4Y2REL7`YB0?_3YX9-:_"\_=UZG
M/OF'4V4XX'G1Y[D@;+"F-#QVQ+';'$-W$C->7'$&>MG9'Y,GT*_0A@0C$AIF
M>5K%ZOVW]<>?#G$SAP14J.-.?A^N"1J:[,B9<=&SCI3G=([YKHU5&)H8&#CT
M8'%/%)!-W>=]AY1L=.1L7%8Q@G/%L.EKKW8YP#2M#1,M;DTT7M2&9D>$<+@:
M:@93%QLV.%"3\<7O/.*>YT%N(7>>I"M3UZOIY15L6SHY6/%I"SS-:ZZ-4(GD
M4-Q"()H<J>@#G#2M]*[#@`W`08Q$#;-=B6]&_/&/(AO;:,-5MYTQ+X]K//D4
MHO1I2&$PI#"]'(/04B";N9&RX]O_9ZBX.S/A0^=:3<VPY229Q)TD*VV$3\B.
M*EU+VY,@)7.SE6KHPHB1Y\WLC*0EF];2WTA[7QI;*FW3D=U^-F'AWU,#6FZ[
M/`O`MTWSTSOI9J^IAQ<X4>_;8]A(=Y!MDUJ+[#;!;>]P;T`H<NP+,U2F3K4E
M>*LW\];FLHG1"K&_1M>+AFS\PALBCW*-$8/=71L4;2@-+[6V7#"./-R;*`NJ
MY'"2!Q.R%NJ+UG+![N`S*VMJ,NJ;%^8$S#[X&T7!V+"&PAXLPTG8/79J.>K-
MOST!\G'SFMZA6Z3(MK9>S2SLP.&9L2+1&3RBPB>Z!TM-]$$0@8EA=;JAO`RN
M%U'[W<;M"M5:+3Y'&CMQ:PPR=\T89,A#%H=WQH]D*LF*HV<:0G\MHD@VXD(8
M?2X2DK?.;PI2"*SV=(]BQ-7M*.%;&LG0\3BOBIT<8]$WVL"56W-`KLK?D,?!
M0R&:,6SE"+F35!.PC2@THD,@SY\0G),3>OE[&!)L@BSC03=CEW:U[%S6]DRA
M]#8<O#G2EKB<.NH`DD,E6?"(0)<)/`F1O31L\(F=5@)C9+RTXV<G=TMEMKL%
MK5=)HD.PDE:FL$%>)CC78&0V])06YW\V6C!R5G>V555>C2[&.=L(%;*#V)HJ
MSFXW.UARV0H<-E0-ZCR,WQD_#>\C!6\/-51PC.AZKW5[2BHZ$!UU[<VR&`53
M1PA!+7;%JS?;2AG2$KP=T,,;U8BZQ\%1<N%#5:<,SG<"ZE;EE-SO@B$*"E:X
MY'&BGR'5$=J/AU[K21][6IWWZ;80J.]89BIM'83")Y2@$+>.-MAJ?8-SB\NV
M,7ZNVC@K"*,&QUC6U$"E#NH:RG!@*GZQ!S&&!/4)[&OT`"`<.+"YLC%ZDQK!
M@A#=63`,[*F9E*`[%2)`R0-ATWOK8X>_XU?)Q3.IE)&HU"P+2=FP&(8E<P>]
MA):BS#,!/!<CRR,MEI0<,[4*&!85&TC2`)`!7AD!(2)LD*FB,N>W2L_7XB/#
MU^<=LPC46]'FY6#CM`@PT-<HU*!$CSI$($\@*A[_'"@GH*@0B2"3C>[R[+FU
M/85I2F0=W+LYLD)QZ)!Q7?+0IN$$FN/'#N[6NIKM3)*X#-.5#-9TG.IE>#6S
MLK1ESTOFKR>X13BFNQVA/GHVUEAFS/LX%$7C+E5JWK-%)C8Y$/D0.EM1`X@<
M]+&@E]H>*7>WT#DY)[FW%*&B%$Q53MU49),XAN"9*5]Y`>@B`:(:B-*3@,2-
M$,<\S[>FU!"VCONA)`DH^FO;KPMIK;8HTS[H=^ONMX>G"12<.QZOD46YI<Q$
M['2`6T?`LF5W25;NZK9PL+CO>PHM?0O:KRA5<HSKNU@0X@.7=,SV3BD&""GF
MV>F**J.K#A#G86BYR%=)&!EI%!PKBXRD.\`!DJ@8`3C?P$0<D+5GB0XG"%ES
MKE6)1NAXS",HAI[@NOHX.R)C`O.>7I[/@>FB8&=Z;[(=4+7$O`($/I!;6JJ6
MES9^!H="'`IY]2B%;T99<4X#$GIDT\=Z5C-*(AB#!3>'3-@"/IM@&A@)H,4&
M[K@7@^<`O"$#IH%RR2]/>LV1F9+R@K"?Q-5BD[?#K^&/L#;XP-BH7N%P?\UV
MT>D>URR9W`.A=2B^<=\,>IRNA]>[,ZO*.Z@30NX>7**P@N?O@+!PB$@<C;=!
M*'\G;+8Y2O<UI41<Z9ZA$-W764FD5-A:ZVHW[&2LRNRC*M/9EWGO\?6><7KO
MW.97B:&/#Z%7,EL'&2L4(\3-*6AB8D,;2#S:X\6+L0^@)H?(%B;:!"1/X)K&
M8(.9%S+@M@TT;>`ALP;</+?>-]TIQT-X\@.X.0@0(KFQ=U?!.^177>GS%0U,
M`BQ;T!M&J4$VPN#>4W"S#8.0`D,H$7_NS^>/GHPY%(@#,2''^4CUPSTW\(B4
MYS@R"\23),U#JA*M!;AK]&;%LS4'36$0XI<MG?ET463B<W:_=Q?G5YOO,R&R
M*$S!BR;;T8KUO:(A2SY?ZYK^8E>8F#:BM-QF&XEM#,R/(81!_B^ZP2!K4Q"8
M7C\8K'Z+3HCTB4(KI:2@#O-EC<"?47/I_M0'L8&T/"QL(&#`*`$&(@+0TCTR
MH,88M#$**E3%5ZY`]\%@P9'P$8>P%X4@Y4*"\!=T?+UXNFU+TDPAX$-D^,V@
M)&VP8)J,4`.TW-(%FRK(C3<GJ2TXAF_%`Q5#BCP-`H!/F`?V0=0YH'/69_;X
M5UK=V>"AT2AL46Y@J;)#P$W5#S#V[\YKDORWWR+@<$3L.[LA$W1[!8#<A]AH
M8!S09T%`Q`*5(^"0[08I!"X5YE3$JVC;&5FF],D[#)9"F$S2IC,U^VW7/W<7
MF'ME48*-#]@?7!AY$,8555<R9V4"2@.],[QX>%G3X3_!N\Z*+[$2,35F!L;X
M;[6+?'FC[@QXK)_UK51J!8OV!?$*6E.0!X@)418PCND.0,#$S-M32J3@>#:8
M%'.;1[34X%Z+$4+6G!>BFH&)H+N(KV!B=H2+1--%1^:(0;4Z:1@3G*=A(@SD
M,=I$"!8I8'(=U#,4#E['5H[.*9`)#$%2AT"`'+&P:+@J?#F%U`B%+\Q!1-4Y
M!D8BAH<`TX[Q'@/<EZO(JTA!TQ1]#(RFDH:\8JW@F6VR-@;JJVD%;-#94Q&V
M$)"!1<WZ*9%<J!>:#7>$+JH8F0TF;&PSL4D:`H*+!!6**(J"YLV^7=OY]MMZ
M^>9S`%'I%QX_;DD*DV!+!;[:E%\0>-3;$_U@!NH>Y/OA`-1K:$.7<D-`&%0-
M7H:,3(=1`LG8$]W=>EU.MR8&&&"X6'(]![BL%T%&I<N%2]XQ"-[F;W2[DMDF
M"U8A+$"#;1D#@P5"!4"WB-8:(NB.$8180A&,8Q&(1P0@CNW3>.F5#"%-$=RB
M1J7HPPH;?(ZN.44#!<4`[P;*"0H4'FX-E4<NT60UYALLFN':_N^;S.S$C")5
M@+0NZG9WJ:BKQ1(`Z2=QZP>#W)Z83)R*A42E2+1S$#9.5#4C4M8@11+U#E&P
MCR$DCAL]W/4R42.1VEG5ENWI(15J69A(&1`5(+"=Y-W=:=Y]5E#CP\!8/4I#
MU/.):I1R4Z@NKH:<B1++]8N%\"6.5JO-9E`)=A0&.8GXU;H;,$,V(*9@[&NU
M!3BUZ*:5$C28JR-!'"_!P\9Q8HR-[&EKE1U\P!\@20Y)`]L.ZP_7IZ?$['_^
MY@<4$S$XI]/)A\5&(2(U5*TLC%&BD#7++)&)*20&%$DH<P"R<D.G8@:T>H.>
M:BF1+OY$($`C($A:=(RD.,?%D8<R;(D-P3<SU[[0H6N7$A+`5)7!Q`P`D(L@
M4=UV[9^H=3GWO^,`\8JF,3?)#(1B23D`+B`,B@]K`2=8?7Q-#0!W`U5\\LSO
M\@+X2=U--*"@-"B&P^WJ3S*#:$8L"<_9;_`+GU#N`[#$5@$8A&1(1D$8!#G+
MC0%]#(A`WW#G4.!P?,'4U)U%9#JS*1[`,$`THEN6;?.P-]2PS@&`P2^5JG`0
MX-VL8:A<@L(,?5`,^%9UV$!,1.F"AXJG.2-CAA>(G>4Q0'H>GG^'%KBL08D(
M-1VM7Q(W>QC95H!&AHL00P*>$_K$9AF7R*%`HR$@OVB!0GS*`(^XL[24(>N=
M@;@AS&\N$`O&<Y0XC0H&P]K$%P&,S&T1<_".E@/28:!1U]GV3V8W4'LR$,4Y
M@^B8?=\/@N(&0AU&/`$]J)21H*>QY@OX03M`XH#!,T)CR8#2-_9B%``0=GK\
MK_T/$.ZD[K"UC6VY#0WM524@*M5:T-]C*8DNB7+6+SF^\B9)T`6X>[CV`ZOQ
M0-ML$UJ9J7;MDL@%FHSO!"73A4444470#,`1B;JIJLH@D8$9&(QNB*0("$$B
MT)<(%#(D$I2,B0@F&)*F(/!-%032"C19J<\V8A8D(-CD3`EHH)17P@;2\AN=
M*X0M$)S"P)`U*S2X<0.HBO57,@*08`4;/"1-X>NQQ0V/N8Q=KGBL,(W7M:M=
MW#8D9-QB*",(@""!Q(!H&TTK`8A)\#2%S2&]*TKZYEB])7LL:VE-78&V6B+?
M`E]R:X^$Q/JWB4/(ZW#BT(6Z-![57`I;`<>'+8]NE\PS1L-\7>0(PEL1_+T]
M?1`^I[U!XF,BDG"HIW52N`+3(/<.V#8@6C$WZBN2!!9$0A%#T(M1&0A!816X
M2(M-":@<"ZF//N!VKBAHJX>=H`2R-*'FA2"&JI``Y8!JTT0'"0W5CS-P=!%@
M%X&@Y:!Q]S=#/50CIWL[J)B)S"DCL(!L!M`U0N=S##7]A-YPNU=0+5JH65M\
MR]2P.+AE`;?(=B,)N4O).0P[#%U[7^/K69Y!.?(N#;308"0!U)G$4-2EYP#(
M0(90VK,`JHT-`+#-2G<8L7FQCB!@@E]YMY[$8X0G#HBP'?9FB`!6<X!Y$DNI
M0+A`D!M&1$*;,(.5%06\8D8B15@PB7&0RK!23V.HV`0PR&3XT;H93RS"IH1-
M'40+L%F4E\4:D.I(2HQE"+H&(&.R3;8TNU!EQH0+JA\GZ#8'Q0S,`B^GB8<*
M"D(:GT.(IAV`?<]_*T.^>(<RWAVR!9LU(&ZF6B@8X/#CDF\HIQI[[W+SE$2(
MD?DKXZEPLDJ-QCE532=$*J$$1L9"ATQLI_W_77;^YUSO5V4T`YT"@#*B+OB@
MTH'B#.3[8'L+$L!XF#8^P&?:>\N(P++25&,)`*(K(I)2)(.&D+E32+IBLB4D
MBN!#PN'<@9YES'IYO39&5^V0I1CD=[S*_Y,UV3MX_@-['/E1-V&!1_3B\S(=
M"XEBV-V>5<KZGVLGG<QFE5,UR$D&F&4+WJN3_E:"R>D%(PN8UVM6`2L2$LQV
M]>F#YYSR26F9H6)C>I%Z_KX>5<.]FE\VZ\50IOMDH.O?6L?QAX5N6-S<3I&T
M9'K8-ON[A)';@P>4TZQL(F=K97JK=%QK=?K8=FT"^!,<F"@P1868PTC9A,D/
M.;/$S24U>K$9::]`.+D58\7J63`X)W/(YM4?*^G9Y^A#:ZRH4!<1=]<^5L]1
MCD-98?+XD(>/+23>[0<'9#,%XR*</$M%`_5EU<`Q(9])8I0,YB&S),=!R#\]
M#][?#D:"'`Z!=0!5J!TKM(&\GS*N_QY^7)KC].X[4\DR#-33CBO1"#$.(=B+
MC!D;RC110HAF$6</&#1@3$A>AC@^!`Q30ZD)1,NIQ0>[0;"15^_AW[Q.\S5`
MR@!H'.'%.\0\_`0R'0>2$(.X0:$"@"XK9-RR':"B15$1$Y20O.S$FH>&SX"0
MBPH@58-V[AVIG7WK47W:.P$TS,SP*'>-Q>>TPP%;=\E5/;)!>[`8!$8$2(T!
MPX\*0VD@&WKV!_BP4OEAEH;R8T1T`'7D3`4&CR"$2;<@.7M.QT*.9S'[8<G0
M4V^8&3;=4[B;A8$.B9@,;IY"*^)Y`\^Q.O/D>HY`:>^1C!0=0Z\0^R2N:+;T
M]IK@?@3H,CU]`NDS@HT=8VXG&X10:*HI^IJU6B8#HMB(JTB#@D84:9<ZJ[\2
M<N2-CA=T%=B*^$$\E3*X'*GY`9F<#Q&"?M0VQNMR@F$+E4R*NY\`&AO`P@86
MJ13E5K>P@.4!L&6</=:^5J5.@X!#FQLJ9Q%L$1J`%?=$5*4S;T4)G42HFK:2
MR,B:0"51Q@A##7M=,$MP6U6/.F[S]0_&@0^\C>KL+B,*E/\:E7NP*/;\6*MQ
M-!>&.LY<\!WG3&]C$M`U"/84Q-MX?X@?GV.0+(/%"_\Y9A+U6"JBF`$Q,4LQ
M"(B2&&JJD080>Z[$?&&PW$$V)A_WIS+C2(/K'YN\>@RY_>,T>QF`L'1Y-1GX
MWL;=C//$-,27JK#U,1EE#BSI'M(;854K*6TKKTXXT=!,L4SOTM5QU*)90_;5
;;;6A9;;W(15&V!V>^7SZO_\7<D4X4)`9Z,).

__
meta::cache('parent-identification', <<'__');
/home/spencertipping/bin/caterwaul-extension.html 5a8b9dacb335276b310735858942e66b
/home/spencertipping/bin/configuration aa772900bb5b925cb84346bd72a4249d
/home/spencertipping/bin/object 99aeabc9ec7fe80b1b39f5e53dc7e49e
/home/spencertipping/bin/repository 05bc3036c343fdb8aec5b0be12a9b19e
/home/spencertipping/conjectures/perl-objects/js 246bc56c88e8e8daae3737dbb16a2a2c
/home/spencertipping/conjectures/perl-objects/sdoc a1e8480e579614c01dabeecf0f963bcc
compressed 520b552d3a50a6c14067471f08aaddab
object 99aeabc9ec7fe80b1b39f5e53dc7e49e
preprocessor 70dae4b46eb4e06798ec6f38d17d4c7b
__
meta::configuration('dependencies', <<'__');
# Caterwaul extensions depend on caterwaul with standard extensions. You can
# also add any additional dependencies here:

bzip2::caterwaul.min.js:     bzip2::http://caterwauljs.org/build/caterwaul.min.js
bzip2::caterwaul.std.min.js: bzip2::http://caterwauljs.org/build/caterwaul.std.min.js

#caterwaul.js:     http://caterwauljs.org/build/caterwaul.js
#caterwaul.std.js: http://caterwauljs.org/build/caterwaul.std.js

#caterwaul.regexp.js: http://spencertipping.com/caterwaul-regexp/regexp.js
#caterwaul.parser.js: http://spencertipping.com/caterwaul-parser/parser.js
#caterwaul.futures.js: http://spencertipping.com/caterwaul-futures/future.js

__
meta::data('author', 'Spencer Tipping');
meta::data('default-action', 'shell');
meta::data('description', <<'__');
This script provides an easy-to-use REPL when writing Caterwaul extensions. It
also renders the extension source to a .js file.

__
meta::data('edit::no-save', '1');
meta::data('license', <<'__');
MIT License
Copyright (c) 2010 Spencer Tipping

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
__
meta::data('permanent-identity', '0ac7cbae894a8d3ca96904e45a3e3398');
meta::function('ad', <<'__');
return @{$transient{path}} = () unless @_;
push @{$transient{path}}, @_;

__
meta::function('alias', <<'__');
my ($name, @stuff) = @_;
@_ ? @stuff ? around_hook('alias', @_, sub {associate("alias::$name", join(' ', @stuff), execute => 1)})
            : retrieve("alias::$name") // "Undefined alias $name"
   : table_display([select_keys('--namespace' => 'alias')], [map retrieve($_), select_keys('--namespace' => 'alias')]);

__
meta::function('cat', 'join "\\n", retrieve(@_);');
meta::function('cc', <<'__');
# Stashes a quick one-line continuation. (Used to remind me what I was doing.)
@_ ? associate('data::current-continuation', hook('set-cc', join(' ', @_))) : retrieve('data::current-continuation');
__
meta::function('ccc', 'rm(\'data::current-continuation\');');
meta::function('child', <<'__');
around_hook('child', @_, sub {
  my ($child_name) = @_;
  clone($child_name);
  enable();
  qx($child_name update-from $0 -n);
  disable()});
__
meta::function('clone', <<'__');
for (grep length, @_) {
  around_hook('clone', $_, sub {
    hypothetically(sub {
      rm('data::permanent-identity');
      file::write($_, serialize(), noclobber => 1);
      chmod(0700, $_)})})}
__
meta::function('compress', <<'__');
# Compresses one or more attributes.
exists $data{$_} or die "$_ doesn't exist; not compressing anything" for @_;
associate("bzip2::$_", compress_data(retrieve($_))), rm($_) for @_;

__
meta::function('cp', <<'__');
my $from = shift @_;
my $value = retrieve($from);
associate($_, $value) for @_;
__
meta::function('create', <<'__');
my ($name, $value) = @_;
around_hook('create', $name, $value, sub {
  return edit($name) if exists $data{$name};
  associate($name, defined $value ? $value : '');
  edit($name) unless defined $value});
__
meta::function('current-state', 'serialize(\'-pS\');');
meta::function('disable', 'hook(\'disable\', chmod_self(sub {$_[0] & 0666}));');
meta::function('dupdate', <<'__');
# Update the repository based on the dependencies it lists. These dependencies
# can be anything that's retrievable.

# If you have any ::s in the local name of the dependency, then the cached_dependency::
# prefix won't be added. This lets you import slices of other objects and have
# those slices merge into any namespace you'd like.

rm(grep /^cached_dependency::/, keys %data);
my %dependencies = map &{attribute($_)}(), select_keys('--criteria' => "^configuration::depend.*");

for (keys %dependencies) {
  terminal::info("Retrieving $dependencies{$_} as $_");
  my $prefix = /::/ ? '' : 'cached_dependency::';
  associate("${prefix}$_", retrieve($dependencies{$_}))}

reload();

__
meta::function('edit', <<'__');
my ($name, %options) = @_;
my $extension = extension_for($name);

die "$name is virtual or does not exist" unless exists $data{$name};
die "$name is inherited; use 'edit $name -f' to edit anyway" unless is($name, '-u') || is($name, '-d') || exists $options{'-f'};

around_hook('edit', @_, sub {
  associate($name, invoke_editor_on($data{$name} // '', %options, attribute => $name, extension => $extension), execute => 1)});
save() unless $data{'data::edit::no-save'};
'';
__
meta::function('enable', 'hook(\'enable\', chmod_self(sub {$_[0] | $_[0] >> 2}));');
meta::function('export', <<'__');
# Exports data into a text file.
#   export attr1 attr2 attr3 ... file.txt
my $name = pop @_;
@_ or die 'Expected filename';
file::write($name, join "\n", retrieve(@_));
__
meta::function('extern', '&{$_[0]}(retrieve(@_[1 .. $#_]));');
meta::function('grep', <<'__');
# Looks through attributes for a pattern. Usage is grep pattern [options], where
# [options] is the format as provided to select_keys.

my ($pattern, @args)     = @_;
my ($options, @criteria) = separate_options(@args);
my @attributes           = select_keys(%$options, '--criteria' => join('|', @criteria));

$pattern = qr/$pattern/;

my @m_attributes;
my @m_line_numbers;
my @m_lines;

for my $k (@attributes) {
  next unless length $k;
  my @lines = split /\n/, retrieve($k);
  for (0 .. $#lines) {
    next unless $lines[$_] =~ $pattern;
    push @m_attributes,   $k;
    push @m_line_numbers, $_ + 1;
    push @m_lines,        '' . ($lines[$_] // '')}}

unless ($$options{'-C'}) {
  s/($pattern)/\033[1;31m\1\033[0;0m/g for @m_lines;
  s/^/\033[1;34m/o for @m_attributes;
  s/^/\033[1;32m/o && s/$/\033[0;0m/o for @m_line_numbers}

table_display([@m_attributes], [@m_line_numbers], [@m_lines]);
__
meta::function('hash', 'fast_hash(@_);');
meta::function('hook', <<'__');
my ($hook, @args) = @_;
$transient{active_hooks}{$hook} = 1;
dangerous('', sub {&$_(@args)}) for grep /^hook::${hook}::/, sort keys %data;
@args;
__
meta::function('hooks', 'join "\\n", sort keys %{$transient{active_hooks}};');
meta::function('identity', 'retrieve(\'data::permanent-identity\') || associate(\'data::permanent-identity\', fast_hash(rand() . name() . serialize()));');
meta::function('import', <<'__');
my $name = pop @_;
associate($name, @_ ? join('', map(file::read($_), @_)) : join('', <STDIN>)); 
__
meta::function('initial-state', '$transient{initial};');
meta::function('is', <<'__');
my ($attribute, @criteria) = @_;
my ($options, @stuff) = separate_options(@criteria);
exists $data{$attribute} and attribute_is($attribute, %$options);

__
meta::function('load-state', <<'__');
around_hook('load-state', @_, sub {
  my ($state_name) = @_;
  my $state = retrieve("state::$state_name");

  terminal::state('saving current state into _...');
  save_state('_');

  delete $data{$_} for grep ! /^state::/, keys %data;
  %externalized_functions = ();

  terminal::state("restoring state $state_name...");
  meta::eval_in($state, "state::$state_name");
  terminal::error(hook('load-state-failed', $@)) if $@;
  reload();
  verify()});

__
meta::function('lock', 'hook(\'lock\', chmod_self(sub {$_[0] & 0555}));');
meta::function('ls', <<'__');
my ($options, @criteria) = separate_options(@_);
my ($external, $shadows, $sizes, $flags, $long, $hashes, $parent_hashes) = @$options{qw(-e -s -z -f -l -h -p)};
$sizes = $flags = $hashes = $parent_hashes = 1 if $long;

return table_display([grep ! exists $data{$externalized_functions{$_}}, sort keys %externalized_functions]) if $shadows;

my $criteria    = join('|', @criteria);
my @definitions = select_keys('--criteria' => $criteria, '--path' => $transient{path}, %$options);

my %inverses  = map {$externalized_functions{$_} => $_} keys %externalized_functions;
my @externals = map $inverses{$_}, grep length, @definitions;
my @internals = grep length $inverses{$_}, @definitions;
my @sizes     = map sprintf('%6d %6d', length(serialize_single($_)), length(retrieve($_))), @{$external ? \@internals : \@definitions} if $sizes;

my @flags     = map {my $k = $_; join '', map(is($k, "-$_") ? $_ : '-', qw(d i m u))} @definitions if $flags;
my @hashes    = map fast_hash(retrieve($_)), @definitions if $hashes;

my %inherited     = parent_attributes(grep /^parent::/o, keys %data) if $parent_hashes;
my @parent_hashes = map $inherited{$_} || '-', @definitions if $parent_hashes;

join "\n", map strip($_), split /\n/, table_display($external ? [grep length, @externals] : [@definitions],
                                                    $sizes ? ([@sizes]) : (), $flags ? ([@flags]) : (), $hashes ? ([@hashes]) : (), $parent_hashes ? ([@parent_hashes]) : ());

__
meta::function('module', <<'__');
my ($name) = @_;

associate("module::$name", <<end);
Module name | Author name
Licensed under the terms of the MIT source code license

Introduction.
This module is called $name.
end

associate('sdoc::js::modules', retrieve('sdoc::js::modules') . "\n- include perl::sdoc('module::$name')\n");

terminal::info("created module $name, which is automatically loaded into REPL sessions.",
               'some relevant commands:',
               '',
               "> edit module::$name  (longhand way to edit stuff)",
               "> $name               (provided by meta::type::module)",
               '> repl',
               '> er       (to edit the REPL script)',
               '> em       (to edit the module list)',
               '> et       (to edit the test script)',
               '> render');

__
meta::function('modules', <<'__');
# Identify the modules defined by the user.
grep s/^module:://, sort keys %data;

__
meta::function('mv', <<'__');
my ($from, $to) = @_;
die "'$from' does not exist" unless exists $data{$from};
associate($to, retrieve($from));
rm($from);
__
meta::function('name', <<'__');
my $name = $0;
$name =~ s/^.*\///;
$name;
__
meta::function('parents', 'join "\\n", grep s/^parent:://o, sort keys %data;');
meta::function('perl', <<'__');
my $result = eval(join ' ', @_);
$@ ? terminal::error($@) : $result;
__
meta::function('preprocess', <<'__');
# Implements a simple preprocessing language.
# Syntax follows two forms. One is the 'line form', which gives you a way to specify arguments inline
# but not spanning multiple lines. The other is 'block form', which gives you access to both one-line
# arguments and a block of lines. The line parameters are passed in verbatim, and the block is
# indentation-adjusted and then passed in as a second parameter. (Indentation is adjusted to align
# with the name of the command.)
#
# Here are the forms:
#
# - line arguments to function
#
# - block line arguments << eof
#   block contents
#   block contents
#   ...
# - eof

my ($string, %options) = @_;
my $expansions         = 0;
my $old_string         = '';
my $limit              = $options{expansion_limit} || 100;
my @pieces             = ();

sub adjust_spaces {
  my ($spaces, $string) = @_;
  $string =~ s/^$spaces  //mg;
  chomp $string;
  $string;
}

while ($old_string ne $string and $expansions++ < $limit) {
  $old_string = $string;

  while ((my @pieces = split  /(^(\h*)-\h \S+ \h* \V* <<\h*(\w+)$ \n .*?  ^\2-\h\3$)/xms, $string) > 1 and $expansions++ < $limit) {
    $pieces[1 + ($_ << 2)] =~ /^ (\h*)-\h(\S+)\h*(\V*)<<\h*(\w+)$ \n(.*?) ^\1-\h\4 $/xms && $externalized_functions{"template::$2"} and
      $pieces[1 + ($_ << 2)] = &{"template::$2"}($3, adjust_spaces($1, $5))
      for 0 .. $#pieces / 4;

    @pieces[2 + ($_ << 2), 3 + ($_ << 2)] = '' for 0 .. $#pieces / 4;
    $string = join '', @pieces;
  }

  if ((my @pieces = split     /^(\h*-\h \S+ \h* .*)$/xom, $string) > 1) {
    $pieces[1 + ($_ << 1)] =~ /^ \h*-\h(\S+)\h*(.*)$/xom && $externalized_functions{"template::$1"} and
      $pieces[1 + ($_ << 1)] = &{"template::$1"}($2)
      for 0 .. $#pieces >> 1;

    $string = join '', @pieces;
  }
}

$string;
__
meta::function('rd', <<'__');
my $pattern = join '|', @_;
@{$transient{path}} = grep $_ !~ /^$pattern$/, @{$transient{path}};

__
meta::function('reload', 'around_hook(\'reload\', sub {execute($_) for grep ! /^bootstrap::/, keys %data});');
meta::function('render', <<'__');
around_hook('render', @_, sub {
  file::write("$_.js",     sdoc("module::$_")) for modules();
  file::write('test.html', retrieve('pp::html::test'))});

__
meta::function('render-min', <<'__');
# Minifies rendered Javascript files.
system("yuicompressor $_.js -o $_.min.js") for modules();

__
meta::function('repl', <<'__');
around_hook('repl', sub {
  with_exported('pp::js::repl', sub {sh('node', @_)})});

__
meta::function('rm', <<'__');
around_hook('rm', @_, sub {
  exists $data{$_} or terminal::warning("$_ does not exist") for @_;
  delete @data{@_}});
__
meta::function('rmparent', <<'__');
# Removes one or more parents.
my ($options, @parents) = separate_options(@_);
my $clobber_divergent = $$options{'-D'} || $$options{'--clobber-divergent'};

for my $parent (@parents) {
  my $keep_parent_around = 0;

  for my $line (split /\n/, retrieve("parent::$parent")) {
    my ($name, $hash) = split /\s+/, $line;
    next unless exists $data{$name};

    my $local_hash = fast_hash(retrieve($name));
    if ($clobber_divergent or $hash eq $local_hash or ! defined $hash) {rm($name)}
    else {terminal::info("local attribute $name exists and is divergent; use rmparent -D $parent to delete it");
          $keep_parent_around = 1}}

  $keep_parent_around ? terminal::info("not deleting parent::$parent so that you can run", "rmparent -D $parent if you want to nuke divergent attributes too")
                      : rm("parent::$parent")}

__
meta::function('save', 'around_hook(\'save\', sub {dangerous(\'\', sub {file::write($0, serialize()); $transient{initial} = state()}) if verify()});');
meta::function('save-state', <<'__');
# Creates a named copy of the current state and stores it.
my ($state_name) = @_;
around_hook('save-state', $state_name, sub {
  associate("state::$state_name", current_state(), execute => 1)});

__
meta::function('sdoc', <<'__');
# Applies SDoc processing to a file or attribute. Takes the file or attribute
# name as the first argument and returns the processed text.

my %comments_for_extension = 
  qw|c     /*,*/  cpp   //    cc   //    h    //    java //  py  #    rb   #    pl  #   pm   #         ml   (*,*)  js  //
     hs    --     sh    #     lisp ;;;   lsp  ;;;   s    ;   scm ;;;  sc   ;;;  as  //  html <!--,-->  mli  (*,*)  cs  //
     vim   "      elisp ;     bas  '     ada  --    asm  ;   awk #    bc   #    boo #   tex  %         fss  (*,*)  erl %
     scala //     hx    //    io   //    j    NB.   lua  --  n   //   m    %    php //  sql  --        pov  //     pro %
     r     #      self  ","   tcl  #     texi @c    tk   #   csh #    vala //   vbs '   v    /*,*/     vhdl --     ss  ;;;
     haml  -#     sass  /*,*/ scss /*,*/ css  /*,*/ fig  /|;

# No extension suggests a shebang line, which generally requires # to denote a comment.
$comments_for_extension{''} = '#';

my $generated_string = 'Generated by SDoc';

sub is_code    {map /^\s*[^A-Z\|\s]/o, @_}
sub is_blank   {map /^\n/o, @_}
sub comment    {my ($text, $s, $e) = @_; join "\n", map("$s $_$e", split /\n/, $text)}

sub paragraphs {map split(/((?:\n\h*){2,})/, $_), @_}

my ($filename) = @_;

# Two possibilities here. One is that the filename is an attribute, in which case
# we want to look up the extension in the transients table. The other is that
# it's a real filename.
my ($extension)       = $filename =~ /\.sdoc$/io ? $filename =~ /\.(\w+)\.sdoc$/igo : $filename =~ /\.(\w+)$/igo;
my ($other_extension) = extension_for($filename);
$other_extension =~ s/\.sdoc$//io;
$other_extension =~ s/^\.//o;

my ($start, $end) = split /,/o, $comments_for_extension{lc($other_extension || $extension)} // $comments_for_extension{''};

join '', map(is_code($_) || is_blank($_) ? ($_ =~ /^\s*c\n(.*)$/so ? $1 : $_) : comment($_, $start, $end), paragraphs retrieve($filename)),
         "\n$start $generated_string $end\n";

__
meta::function('sdoc-html', <<'__');
# Converts SDoc to logically-structured HTML. Sections end up being nested,
# and code sections and examples are marked as such. For instance, here is some
# sample output:

# <div class='section level1'>
#   <h1 class='title'>Foo</h1>
#   <p>This is a paragraph...</p>
#   <p>This is another paragraph...</p>
#   <pre class='code'>int main () {return 0;}</pre>
#   <pre class='quoted'>int main () {return 0} // Won't compile</pre>
#   <div class='section level2'>
#     <h2 class='title'>Bar</h2>
#     ...
#   </div>
# </div>

# It is generally good about escaping things that would interfere with HTML,
# but within text paragraphs it lets you write literal HTML. The heuristic is
# that known tags that are reasonably well-formed are allowed, but unknown ones
# are escaped.

my ($attribute)   = @_;
my @paragraphs    = split /\n(?:\s*\n)+/, retrieve($attribute);

my $known_tags    = join '|', qw[html head body meta script style link title div a span input button textarea option select form label iframe blockquote code caption
                                 table tbody tr td th thead tfoot img h1 h2 h3 h4 h5 h6 li ol ul noscript p pre samp sub sup var canvas audio video];
my $section_level = 0;
my @markup;

my $indent        = sub {'  ' x ($_[0] || $section_level)};
my $unindent      = sub {my $spaces = '  ' x ($section_level - 1); s/^$spaces//gm};

my $escape_all    = sub {s/&/&amp;/g; s/</&lt;/g; s/>/&gt;/g};
my $escape_some   = sub {s/&/&amp;/g; s/<(?!\/|($known_tags)[^>]*>.*<\/\1>)/&lt;/gs};

my $code          = sub {&$escape_all(); &$unindent(); s/^c\n//;                   push @markup, &$indent() . "<pre class='code'>$_</pre>"};
my $quoted        = sub {&$escape_all(); &$unindent(); s/^\|(\s?)/ \1/; s/^  //mg; push @markup, &$indent() . "<pre class='quoted'>$_</pre>"};

my $paragraph     = sub {&$escape_some(); push @markup, &$indent() . "<p>$_</p>"};

my $section       = sub {my $h = $_[0] > 6 ? 6 : $_[0]; push @markup, &$indent($_[0] - 1) . "<div class='section level$_[0]'>", &$indent($_[0]) . "<h$h>$2</h$h>"};
my $close_section = sub {push @markup, &$indent($_[0]) . "</div>"};

my $title = sub {
  my $indentation = (length($1) >> 1) + 1;
  &$close_section($section_level) while $section_level-- >= $indentation;
  &$section($indentation);
  $section_level = $indentation;
};

for (@paragraphs) {
  &$code(),   next unless /^\h*[A-Z|]/;
  &$quoted(), next if     /^\h*\|/;

  &$title(), s/^.*\n// if /^(\s*)(\S.*)\.\n([^\n]+)/ and length("$1$2") - 10 < length($3);
  &$paragraph();
}

&$close_section($section_level) while $section_level--;

join "\n", @markup;
__
meta::function('sdocp', <<'__');
# Renders an attribute as SDocP. This logic was taken directly from the sdoc script.
my $attribute = retrieve($_[0]);
sub escape {my @results = map {s/\\/\\\\/go; s/\n/\\n/go; s/'/\\'/go; $_} @_; wantarray ? @results : $results[0]}
"sdocp('" . escape($_[0]) . "', '" . escape($attribute) . "');";
__
meta::function('serialize', <<'__');
my ($options, @criteria) = separate_options(@_);
my $partial     = $$options{'-p'};
my $criteria    = join '|', @criteria;
my @attributes  = map serialize_single($_), select_keys(%$options, '-m' => 1, '--criteria' => $criteria), select_keys(%$options, '-M' => 1, '--criteria' => $criteria);
my @final_array = @{$partial ? \@attributes : [retrieve('bootstrap::initialization'), @attributes, 'internal::main();', '', '__END__']};
join "\n", @final_array;
__
meta::function('serialize-single', <<'__');
# Serializes a single attribute and optimizes for content.

my $name          = $_[0] || $_;
my $contents      = $data{$name};
my $meta_function = 'meta::' . namespace($name);
my $invocation    = attribute($name);
my $escaped       = $contents;
$escaped =~ s/\\/\\\\/go;
$escaped =~ s/'/\\'/go;

return "$meta_function('$invocation', '$escaped');" unless $escaped =~ /\v/;

my $delimiter = '__' . fast_hash($contents);
my $chars     = 2;

++$chars until $chars >= length($delimiter) || index("\n$contents", "\n" . substr($delimiter, 0, $chars)) == -1;
$delimiter = substr($delimiter, 0, $chars);

"$meta_function('$invocation', <<'$delimiter');\n$contents\n$delimiter";
__
meta::function('sh', 'system(@_);');
meta::function('shb', <<'__');
# Backgrounded shell job.
exec(@_) unless fork;

__
meta::function('shell', <<'__');
my ($options, @arguments) = separate_options(@_);
$transient{repl_prefix} = $$options{'--repl-prefix'};

terminal::cc(retrieve('data::current-continuation')) if length $data{'data::current-continuation'};
around_hook('shell', sub {shell::repl(%$options)});

__
meta::function('size', <<'__');
my $size = 0;
$size += length $data{$_} for keys %data;
sprintf "% 7d % 7d % 7d", length(serialize()), $size, length(serialize('-up'));

__
meta::function('snapshot', <<'__');
my ($name) = @_;
file::write(my $finalname = temporary_name($name), serialize(), noclobber => 1);
chmod 0700, $finalname;
hook('snapshot', $finalname);
__
meta::function('state', <<'__');
my @keys = sort keys %data;
my $hash = fast_hash(fast_hash(scalar @keys) . join '|', @keys);
$hash = fast_hash("$data{$_}|$hash") for @keys;
$hash;
__
meta::function('test', <<'__');
around_hook('test', sub {
  with_exported('pp::js::test-setup', sub {sh('node', @_)})});

__
meta::function('touch', 'associate($_, \'\') for @_;');
meta::function('uncompress', <<'__');
# Compresses one or more attributes.
exists $data{"bzip2::$_"} or die "bzip2::$_ doesn't exist; not uncompressing anything" for @_;
associate($_, uncompress_data(retrieve("bzip2::$_"))), rm("bzip2::$_") for @_;

__
meta::function('unlock', 'hook(\'unlock\', chmod_self(sub {$_[0] | 0200}));');
meta::function('update', <<'__');
update_from(@_, grep s/^parent:://o, sort keys %data);

__
meta::function('update-from', <<'__');
# Upgrade all attributes that aren't customized. Customization is defined when the data type is created,
# and we determine it here by checking for $transient{inherit}{$type}.

# Note that this assumes you trust the remote script. If you don't, then you shouldn't update from it.

around_hook('update-from-invocation', separate_options(@_), sub {
  my ($options, @targets) = @_;
  my %parent_id_cache = cache('parent-identification');
  my %already_seen;

  @targets or return;

  my @known_targets     = grep s/^parent:://, parent_ordering(map "parent::$_", grep exists $data{"parent::$_"}, @targets);
  my @unknown_targets   = grep ! exists $data{"parent::$_"}, @targets;
  @targets = (@known_targets, @unknown_targets);

  my $save_state        = ! ($$options{'-n'} || $$options{'--no-save'});
  my $no_parents        =    $$options{'-P'} || $$options{'--no-parent'} || $$options{'--no-parents'};
  my $force             =    $$options{'-f'} || $$options{'--force'};
  my $clobber_divergent =    $$options{'-D'} || $$options{'--clobber-divergent'};

  save_state('before-update') if $save_state;

  for my $target (@targets) {
    dangerous("updating from $target", sub {
    around_hook('update-from', $target, sub {
      my $identity = $parent_id_cache{$target} ||= join '', qx($target identity);
      next if $already_seen{$identity};
      $already_seen{$identity} = 1;

      my $attributes = join '', qx($target ls -ahiu);
      my %divergent;
      die "skipping unreachable $target" unless $attributes;

      for my $to_rm (split /\n/, retrieve("parent::$target")) {
        my ($name, $hash) = split(/\s+/, $to_rm);
        next unless exists $data{$name};

        my $local_hash = fast_hash(retrieve($name));
        if ($clobber_divergent or $hash eq $local_hash or ! defined $hash) {rm($name)}
        else {terminal::info("preserving local version of divergent attribute $name (use update -D to clobber it)");
              $divergent{$name} = retrieve($name)}}

      associate("parent::$target", $attributes) unless $no_parents;

      dangerous('', sub {eval qx($target serialize -ipmu)});
      dangerous('', sub {eval qx($target serialize -ipMu)});

      map associate($_, $divergent{$_}), keys %divergent unless $clobber_divergent;

      reload()})})}

  cache('parent-identification', %parent_id_cache);

  if (verify()) {hook('update-from-succeeded', $options, @targets);
                 terminal::info("Successfully updated. Run 'load-state before-update' to undo this change.") if $save_state}
  elsif ($force) {hook('update-from-failed', $options, @targets);
                  terminal::warning('Failed to verify: at this point your object will not save properly, though backup copies will be created.',
                                    'Run "load-state before-update" to undo the update and return to a working state.') if $save_state}
  else {hook('update-from-failed', $options, @targets);
        terminal::error('Verification failed after the upgrade was complete.');
        terminal::info("$0 has been reverted to its pre-upgrade state.", "If you want to upgrade and keep the failure state, then run 'update-from $target --force'.") if $save_state;
        return load_state('before-update') if $save_state}});

__
meta::function('usage', '"Usage: $0 action [arguments]\\nUnique actions (run \'$0 ls\' to see all actions):" . ls(\'-u\');');
meta::function('verify', <<'__');
file::write(my $other = $transient{temporary_filename} = temporary_name(), my $serialized_data = serialize());
chomp(my $observed = join '', qx|perl '$other' state|);

unlink $other if my $result = $observed eq (my $state = state());
terminal::error("Verification failed; expected $state but got $observed from $other") unless $result;
hook('after-verify', $result, observed => $observed, expected => $state);
$result;
__
meta::hook('before-shell::note-about-module-function', <<'__');
terminal::info('use the "module" function to create a new Javascript file; e.g:', '',
               '> module foo', '',
               'this will create an attribute sdoc::js::foo and will append a preprocessor',
               'entry to sdoc::js::repl.', '',
               'defined modules:', map("  $_", modules()));

__
meta::indicator('cc', 'length ::retrieve(\'data::current-continuation\') ? "\\033[1;36mcc\\033[0;0m" : \'\';');
meta::indicator('locked', 'is_locked() ? "\\033[1;31mlocked\\033[0;0m" : \'\';');
meta::indicator('path', <<'__');
join "\033[1;30m|\033[0;0m", @{$transient{path}};

__
meta::internal_function('around_hook', <<'__');
# around_hook('hookname', @args, sub {
#   stuff;
# });

# Invokes 'before-hookname' on @args before the sub runs, invokes the
# sub on @args, then invokes 'after-hookname' on @args afterwards.
# The after-hook is not invoked if the sub calls 'die' or otherwise
# unwinds the stack.

my $hook = shift @_;
my $f    = pop @_;

hook("before-$hook", @_);
my $result = &$f(@_);
hook("after-$hook", @_);
$result;
__
meta::internal_function('associate', <<'__');
my ($name, $value, %options) = @_;
die "Namespace does not exist" unless exists $datatypes{namespace($name)};
$data{$name} = $value;
execute($name) if $options{'execute'};
$value;
__
meta::internal_function('attribute', <<'__');
my ($name) = @_;
$name =~ s/^[^:]*:://;
$name;
__
meta::internal_function('attribute_is', <<'__');
my ($a, %options) = @_;
my %inherited     = parent_attributes(grep /^parent::/o, sort keys %data) if grep exists $options{$_}, qw/-u -U -d -D/;
my $criteria      = $options{'--criteria'} || $options{'--namespace'} && "^$options{'--namespace'}::" || '.';
my $path          = $options{'--path'} ? join('|', @{$options{'--path'}}) : '.';

my %tests = ('-u' => sub {! $inherited{$a}},
             '-d' => sub {$inherited{$a} && fast_hash(retrieve($a)) ne $inherited{$a}},
             '-i' => sub {$transient{inherit}{namespace($a)}},
             '-s' => sub {$a =~ /^state::/o},
             '-m' => sub {$a =~ /^meta::/o});

return 0 unless scalar keys %tests == scalar grep ! exists $options{$_}    ||   &{$tests{$_}}(), keys %tests;
return 0 unless scalar keys %tests == scalar grep ! exists $options{uc $_} || ! &{$tests{$_}}(), keys %tests;
$a =~ /$criteria/ and $a =~ /$path/;

__
meta::internal_function('cache', <<'__');
my ($name, %pairs) = @_;
if (%pairs) {associate("cache::$name", join "\n", map {$pairs{$_} =~ s/\n//g; "$_ $pairs{$_}"} sort keys %pairs)}
else        {map split(/\s/, $_, 2), split /\n/, retrieve("cache::$name")}
__
meta::internal_function('chmod_self', <<'__');
my ($mode_function)      = @_;
my (undef, undef, $mode) = stat $0;
chmod &$mode_function($mode), $0;
__
meta::internal_function('compress_data', <<'__');
use IO::Compress::Bzip2 qw/bzip2/;
my ($data) = @_;
my $output = '';
bzip2 \$data => \$output;
pack 'u*', $output;

__
meta::internal_function('dangerous', <<'__');
# Wraps a computation that may produce an error.
my ($message, $computation) = @_;
terminal::info($message) if $message;
my @result = eval {&$computation()};
terminal::warning(translate_backtrace($@)), return undef if $@;
wantarray ? @result : $result[0];
__
meta::internal_function('debug_trace', <<'__');
terminal::debug(join ', ', @_);
wantarray ? @_ : $_[0];
__
meta::internal_function('execute', <<'__');
my ($name, %options) = @_;
my $namespace = namespace($name);
eval {&{$datatypes{$namespace}}(attribute($name), retrieve($name))};
warn $@ if $@ && $options{'carp'};

__
meta::internal_function('exported', <<'__');
# Allocates a temporary file containing the concatenation of attributes you specify,
# and returns the filename. The filename will be safe for deletion anytime.
my $filename = temporary_name();
file::write($filename, cat(@_));
$filename;
__
meta::internal_function('extension_for', <<'__');
my $extension = $transient{extension}{namespace($_[0])};
$extension = &$extension($_[0]) if ref $extension eq 'CODE';
$extension || '';
__
meta::internal_function('fast_hash', <<'__');
my ($data)     = @_;
my $piece_size = length($data) >> 3;

my @pieces     = (substr($data, $piece_size * 8) . length($data), map(substr($data, $piece_size * $_, $piece_size), 0 .. 7));
my @hashes     = (fnv_hash($pieces[0]));

push @hashes, fnv_hash($pieces[$_ + 1] . $hashes[$_]) for 0 .. 7;

$hashes[$_] ^= $hashes[$_ + 4] >> 16 | ($hashes[$_ + 4] & 0xffff) << 16 for 0 .. 3;
$hashes[0]  ^= $hashes[8];

sprintf '%08x' x 4, @hashes[0 .. 3];
__
meta::internal_function('file::read', <<'__');
my $name = shift;
open my($handle), "<", $name;
my $result = join "", <$handle>;
close $handle;
$result;
__
meta::internal_function('file::write', <<'__');
use File::Path     'mkpath';
use File::Basename 'dirname';

my ($name, $contents, %options) = @_;
die "Choosing not to overwrite file $name" if $options{noclobber} and -f $name;
mkpath(dirname($name)) if $options{mkpath};

open my($handle), $options{append} ? '>>' : '>', $name or die "Can't open $name for writing";
print $handle $contents;
close $handle;
__
meta::internal_function('fnv_hash', <<'__');
# A rough approximation to the Fowler-No Voll hash. It's been 32-bit vectorized
# for efficiency, which may compromise its effectiveness for short strings.

my ($data) = @_;

my ($fnv_prime, $fnv_offset) = (16777619, 2166136261);
my $hash                     = $fnv_offset;
my $modulus                  = 2 ** 32;

$hash = ($hash ^ ($_ & 0xffff) ^ ($_ >> 16)) * $fnv_prime % $modulus for unpack 'L*', $data . substr($data, -4) x 8;
$hash;
__
meta::internal_function('hypothetically', <<'__');
# Applies a temporary state and returns a serialized representation.
# The original state is restored after this, regardless of whether the
# temporary state was successful.

my %data_backup   = %data;
my ($side_effect) = @_;
my $return_value  = eval {&$side_effect()};
%data = %data_backup;

die $@ if $@;
$return_value;
__
meta::internal_function('internal::main', <<'__');
disable();

$SIG{'INT'} = sub {snapshot(); exit 1};

$transient{initial}      = state();
chomp(my $default_action = retrieve('data::default-action'));

my $function_name = shift(@ARGV) || $default_action || 'usage';
terminal::warning("unknown action: '$function_name'") and $function_name = 'usage' unless $externalized_functions{$function_name};

around_hook('main-function', $function_name, @ARGV, sub {
  dangerous('', sub {
    chomp(my $result = &$function_name(@ARGV));
    print "$result\n" if $result})});

save() unless state() eq $transient{initial};

END {
  enable();
}
__
meta::internal_function('invoke_editor_on', <<'__');
my ($data, %options) = @_;
my $editor    = $options{editor} || $ENV{VISUAL} || $ENV{EDITOR} || die 'Either the $VISUAL or $EDITOR environment variable should be set to a valid editor';
my $options   = $options{options} || $ENV{VISUAL_OPTS} || $ENV{EDITOR_OPTS} || '';
my $attribute = $options{attribute};
$attribute =~ s/\//-/g;
my $filename  = temporary_name() . "-$attribute$options{extension}";

file::write($filename, $data);
system("$editor $options '$filename'");

my $result = file::read($filename);
unlink $filename;
$result;
__
meta::internal_function('is_locked', '!((stat($0))[2] & 0222);');
meta::internal_function('namespace', <<'__');
my ($name) = @_;
$name =~ s/::.*$//;
$name;
__
meta::internal_function('parent_attributes', <<'__');
my $attributes = sub {my ($name, $value) = split /\s+/o, $_; $name => ($value || 1)};
map &$attributes(), split /\n/o, join("\n", retrieve(@_));
__
meta::internal_function('parent_ordering', <<'__');
# Topsorts the parents by dependency chain. The simplest way to do this is to
# transitively compute the number of parents referred to by each parent.

my @parents = @_;
my %all_parents = map {$_ => 1} @parents;

my %parents_of = map {
  my $t = $_;
  my %attributes = parent_attributes($_);
  $t => [grep /^parent::/, keys %attributes]} @parents;

my %parent_count;
my $parent_count;
$parent_count = sub {
  my ($key) = @_;
  return $parent_count{$key} if exists $parent_count{$key};
  my $count = 0;
  $count += $parent_count->($_) + exists $data{$_} for @{$parents_of{$key}};
  $parent_count{$key} = $count};

my %inverses;
push @{$inverses{$parent_count->($_)} ||= []}, $_ for @parents;
grep exists $all_parents{$_}, map @{$inverses{$_}}, sort keys %inverses;
__
meta::internal_function('retrieve', <<'__');
my @results = map defined $data{$_} ? $data{$_} : retrieve_with_hooks($_), @_;
wantarray ? @results : $results[0];
__
meta::internal_function('retrieve_with_hooks', <<'__');
# Uses the hooks defined in $transient{retrievers}, and returns undef if none work.
my ($attribute) = @_;
my $result      = undef;

defined($result = &$_($attribute)) and return $result for map $transient{retrievers}{$_}, sort keys %{$transient{retrievers}};
return undef;
__
meta::internal_function('select_keys', <<'__');
my %options = @_;
grep attribute_is($_, %options), sort keys %data;
__
meta::internal_function('separate_options', <<'__');
# Things with one dash are short-form options, two dashes are long-form.
# Characters after short-form are combined; so -auv4 becomes -a -u -v -4.
# Also finds equivalences; so --foo=bar separates into $$options{'--foo'} eq 'bar'.
# Stops processing at the -- option, and removes it. Everything after that
# is considered to be an 'other' argument.

# The only form not supported by this function is the short-form with argument.
# To pass keyed arguments, you need to use long-form options.

my @parseable;
push @parseable, shift @_ until ! @_ or $_[0] eq '--';

my @singles = grep /^-[^-]/, @parseable;
my @longs   = grep /^--/,    @parseable;
my @others  = grep ! /^-/,   @parseable;

my @singles = map /-(.{2,})/ ? map("-$_", split(//, $1)) : $_, @singles;

my %options;
/^([^=]+)=(.*)$/ and $options{$1} = $2 for @longs;
++$options{$_} for grep ! /=/, @singles, @longs;

({%options}, @others, @_);

__
meta::internal_function('strip', 'wantarray ? map {s/^\\s*|\\s*$//g; $_} @_ : $_[0] =~ /^\\s*(.*?)\\s*$/ && $1;');
meta::internal_function('table_display', <<'__');
# Displays an array of arrays as a table; that is, with alignment. Arrays are
# expected to be in column-major order.

sub maximum_length_in {
  my $maximum = 0;
  length > $maximum and $maximum = length for @_;
  $maximum;
}

my @arrays    = @_;
my @lengths   = map maximum_length_in(@$_), @arrays;
my @row_major = map {my $i = $_; [map $$_[$i], @arrays]} 0 .. $#{$arrays[0]};
my $format    = join '  ', map "%-${_}s", @lengths;

join "\n", map strip(sprintf($format, @$_)), @row_major;
__
meta::internal_function('temporary_name', <<'__');
use File::Temp 'tempfile';
my (undef, $temporary_filename) = tempfile("$0." . 'X' x 4, OPEN => 0);
$temporary_filename;
__
meta::internal_function('translate_backtrace', <<'__');
my ($trace) = @_;
$trace =~ s/\(eval (\d+)\)/$locations{$1 - 1}/g;
$trace;
__
meta::internal_function('uncompress_data', <<'__');
use IO::Uncompress::Bunzip2 qw/bunzip2/;
my ($packed) = @_;
my $data   = join '', unpack 'u*', $packed;
my $output = '';
bunzip2 \$data => \$output;
$output;

__
meta::internal_function('with_exported', <<'__');
# Like exported(), but removes the file after running some function.
# Usage is with_exported(@files, sub {...});
my $f      = pop @_;
my $name   = exported(@_);
my $result = eval {&$f($name)};
terminal::warning("$@ when running with_exported()") if $@;
unlink $name;
$result;
__
meta::library('shell', <<'__');
# Functions for shell parsing and execution.
package shell;
use Term::ReadLine;

sub tokenize {grep length, split /\s+|("[^"\\]*(?:\\.)?")/o, join ' ', @_};

sub parse {
  my ($fn, @args) = @_;
  s/^"(.*)"$/\1/o, s/\\\\"/"/go for @args;
  {function => $fn, args => [@args]}}

sub execute {
  my %command = %{$_[0]};
  die "undefined command: $command{function}" unless exists $externalized_functions{$command{function}};
  &{"::$command{function}"}(@{$command{args}})}

sub run {execute(parse(tokenize(@_)))}

sub prompt {
  my %options = @_;
  my $name    = $options{name} // ::name();

  my $indicators = join '', map &{"::$_"}(), ::select_keys('--namespace' => 'indicator');
  my $prefix     = $transient{repl_prefix} // '';

  "$prefix\033[1;32m$name\033[0;0m$indicators "}

sub repl {
  my %options = @_;

  my $term = new Term::ReadLine "$0 shell";
  $term->ornaments(0);
  my $attribs = $term->Attribs;
  $attribs->{completion_entry_function} = $attribs->{list_completion_function};

  my $autocomplete = $options{autocomplete} || sub {[sort(keys %data), grep !/-/, sort keys %externalized_functions]};
  my $prompt       = $options{prompt}       || \&prompt;
  my $parse        = $options{parse}        || sub {parse(tokenize(@_))};
  my $command      = $options{command}      || sub {my ($command) = @_; ::around_hook('shell-command', $command, sub {print ::dangerous('', sub {execute($command)}), "\n"})};

  length $_ && &$command(&$parse($_)) while ($attribs->{completion_word} = &$autocomplete(), defined($_ = $term->readline(&$prompt())))}

__
meta::library('terminal', <<'__');
# Functions for nice-looking terminal output.
package terminal;

my $process = ::name();

sub message {print STDERR "[$_[0]] $_[1]\n"}
sub color {
  my ($name, $color) = @_;
  *{"terminal::$name"} = sub {chomp($_), print STDERR "\033[1;30m$process(\033[1;${color}m$name\033[1;30m)\033[0;0m $_\n" for map join('', $_), @_}}

my %preloaded = (info => 32, progress => 32, state => 34, debug => 34, warning => 33, error => 31);
color $_, $preloaded{$_} for keys %preloaded;
__
meta::message_color('cc', '36');
meta::message_color('state', 'purple');
meta::message_color('states', 'yellow');
meta::parent('/home/spencertipping/bin/caterwaul-extension.html', <<'__');
function::module                                            cd75ead8fad4b21dd5e29bc85a2de334
function::modules                                           e3b6934465aed29eebaa08eef3be15fd
function::render                                            41e9d01f7b705950c999151c13224573
function::render-min                                        cb3f9c66145044d3f4c054db0911504b
function::repl                                              878e54fa550b881619f987a9d676038b
function::test                                              af8715c7a61b18bfe7d0e2e72469dfea
meta::type::module                                          4dd84ea154141e3559df4bb6612393c1
parent::/home/spencertipping/bin/repository                 c9d4572a563910ccc4e3defd9fa638f8
parent::/home/spencertipping/conjectures/perl-objects/js    a7e83594e1d17b121d4e566bc2d6c18d
parent::/home/spencertipping/conjectures/perl-objects/sdoc  739656777fc0bcad0d9b72d77c4302bc
parent::preprocessor                                        7172206e753310217b5f67ac8366c8bf
sdoc::html::test                                            69631229b55eddc4f7402badb13f4fe1
sdoc::js::console                                           6b315e3398a0669509f353a260f11716
sdoc::js::dependencies                                      f98fdf7af0dc93d98f0392aff155c9cf
sdoc::js::modules                                           2ff90d3bfe72d95e62d6bbfc4e99273c
sdoc::js::repl                                              b194397d2c44e51527d58f22ae48b43f
sdoc::js::test                                              eea2d2f5909703e105fe1373ea4b1757
sdoc::js::test-setup                                        c8b68de30eece1fcbace6add858c76eb

__
meta::parent('/home/spencertipping/bin/configuration', <<'__');
meta::type::configuration                7f5ba514d47ac29a3c226d0e331d9da4
parent::/home/spencertipping/bin/object  7374722eec54c39ab752e3fb032c1886

__
meta::parent('/home/spencertipping/bin/object', <<'__');
bootstrap::html                         f44dd03cb0c904b3a5f69fbda5f018d0
bootstrap::initialization               1cf74e7209f32722a79b6e49e3907fd3
bootstrap::perldoc                      5793df44bdd2526bb461272924abfd4b
function::ad                            77a05d9a6fef7871b2c3e8e94b56870a
function::alias                         8eeeeb4e064ef3aba7edf8f254427bc2
function::cat                           f684de6c8776617a437b76009114f52e
function::cc                            12ea9176e388400704d823433c209b7a
function::ccc                           d151a9793edd83f80fb880b7f0ab9b34
function::child                         f5764adf0b4e892f147a9b6b68d4816f
function::clone                         bb42e04e10a8e54e88786b6fbc4fb213
function::cp                            3fe69d1b58d90045ad520048977538c4
function::create                        3010d55f4dfa59a998742e07823ed54d
function::current-state                 6f03f86f1901e9ef07fdb5d4079a914c
function::disable                       53b449708cc2ffdefa352e53bb7d847d
function::edit                          9ce5ba1ae4607e8cf1975080bcde1cf4
function::enable                        7de1cedc36841f5de8f9fdfbc3b65097
function::export                        2374cd1dbf7616cb38cafba4e171075d
function::extern                        1290a5223e2824763eecfb3a54961eff
function::grep                          55c3cea8ff4ec2403be2a9d948e59f14
function::hash                          6ee131d093e95b80039b4df9c7c84a02
function::hook                          675cdb98b5dd8567bdd5a02ead6184b5
function::hooks                         3d989899c616f7440429a2d9bf1cc44b
function::identity                      6523885762fcc2f354fc25cf6ed126ce
function::import                        5d0f0634cbd01274f2237717507198a2
function::initial-state                 03d8ed608855a723124e79ca184d8e73
function::is                            41564c8f21b12ab80824ac825266d805
function::load-state                    b6cf278a1f351f316fa6e070359b6081
function::lock                          5d8db258704e6a8623fac796f62fac02
function::ls                            01a23d51d5b529e03943bd57e33f92df
function::mv                            4a0e338a6edb89ad1e2c779d51d4d47b
function::name                          955ba2d1fe1d67cd78651a4042283b00
function::parents                       3da9e63b5aae9e2f5dcc946a86d166aa
function::perl                          a0f341ea54391b63b6195e7992b6a686
function::rd                            eea4e1cdd9133abb985205ae5daf5f15
function::reload                        1589f4cf8374e0011991cb8907afca3e
function::rm                            6f6fd7a6c25558eb469d78ea888f8551
function::rmparent                      49051d669554867f87c08656380a8aba
function::save                          778c0e1043b9c6c96fb8f266f8061624
function::save-state                    5af59ebc4ad8965767e4dc106d3b557e
function::serialize                     a19ada2d2558ea9da3a7942fb913e15f
function::serialize-single              aa77af032272f5a2664e21713739a223
function::sh                            1b2f542ca9dd63ad437058b7f6f61aac
function::shb                           7b2685a4041c25bc495816e472bdace5
function::shell                         a87f389b94713e5855e62241d649d01d
function::size                          8d4bd7a84ece556717f8ba3bf258d33c
function::snapshot                      56939a47f2758421669641e15ebd66eb
function::state                         8c68044dccae28f33244d0c7e9e9acfb
function::touch                         3991b1b7c7187566f50e5e58ce01fa06
function::unlock                        b4aac02f7f3fb700acf4acfd9b180ceb
function::update                        ac391dc90e507e7586c81850e7c2ecdd
function::update-from                   631721c4dc30e11b2023a6703cbcef52
function::usage                         5bdd370f5a56cfbf199e08d398091444
function::verify                        0c0cc1dfeab7d705919df122f7850a4f
indicator::cc                           3db7509c521ee6abfedd33d5f0148ed3
indicator::locked                       fc2b4f4ca0d6a334b9ac423d06c8f18c
indicator::path                         8a9685787cda6af8f63594f6dcde7582
internal_function::around_hook          7cc876e7c5f78c34654337fc95255587
internal_function::associate            05a75afb70daee635eefec8ae037f593
internal_function::attribute            dd6f010f9688977464783f60f5b6d3dd
internal_function::attribute_is         a145549f6ce44abbcf66308b426d30ec
internal_function::cache                eb9da45580a9ac0882baf98acd2ecd60
internal_function::chmod_self           2035e861eedab55ba0a9f6f5a068ca70
internal_function::dangerous            46c4baaa214ab3d05af43e28083d5141
internal_function::debug_trace          0faf9d9f4159d72dfe4481f6f3607ce1
internal_function::execute              f0924e087d978ff2ab1e117124db3042
internal_function::exported             3ec48f01deefa840b52111f2e3f34749
internal_function::extension_for        9de8261d69cc93e9b92072b89c89befd
internal_function::fast_hash            ee5eba48f837fda0fe472645fdd8899a
internal_function::file::read           e647752332c8e05e81646a3ff98f9a8e
internal_function::file::write          3e290fdcb353c6f842eb5a40f2e575f8
internal_function::fnv_hash             c36d56f1e13a60ae427afc43ba025afc
internal_function::hypothetically       b83e3f894a6df8623ccd370515dfd976
internal_function::internal::main       f31f2945a19a668d92505f114ab29c78
internal_function::invoke_editor_on     5eb976796f0ec172d6ec036116a2f41e
internal_function::is_locked            da12ced6aa38295251f7e748ffd22925
internal_function::namespace            784d2e96003550681a4ae02b8d6d0a27
internal_function::parent_attributes    f6ccfaa982ab1a4d066043981aaca277
internal_function::parent_ordering      57b6da88f76b59f3fed9abfa61280e5e
internal_function::retrieve             8a34d1fe047fe1b40c3d2957c4a789eb
internal_function::retrieve_with_hooks  0f1b0220ccd973d57a2e96ff00458cf2
internal_function::select_keys          a5e3532ec6d58151d0ee24416ea1e2b5
internal_function::separate_options     34ec41a6edaa15adde607a0db3ccfa36
internal_function::strip                14f490b10ebd519e829d8ae20ea4d536
internal_function::table_display        d575f4dc873b2e0be5bd7352047fd904
internal_function::temporary_name       6f548d101fc68356515ffd0fc9ae0c93
internal_function::translate_backtrace  d77a56d608473b3cd8a3c6cb84185e10
internal_function::with_exported        df345d5095d5ed13328ddd07ea922b36
library::shell                          6b9f3befb61a01e9132a440601f8ea0a
library::terminal                       7e2d045782405934a9614fe04bcfe559
message_color::cc                       2218ef0f7425de5c717762ffb100eb43
message_color::state                    03621cd6ac0b1a40d703f41e26c5807f
message_color::states                   ac66eeeff487b5f43f88a78ea18b3d56
meta::configure                         69c2e727c124521d074fde21f8bbc4db
meta::externalize                       aa44e27e0bbee6f0ca4de25d603a1fc7
meta::functor::editable                 48246c608f363de66511400e00b26164
meta::type::alias                       889d26d2df385e9ff8e2da7de4e48374
meta::type::bootstrap                   51108ab2ddb8d966e927c8f62d9ef3e5
meta::type::cache                       9267171f2eace476f64a1a670eaaf2c7
meta::type::data                        120e1649a468d3b3fd3fb783b4168499
meta::type::function                    8ea626198861dc59dd7f303eecb5ff88
meta::type::hook                        ff92aef328b6bdc6f87ddd0821f3e42f
meta::type::inc                         78e0375b6725487cb1f0deca41e96bbe
meta::type::indicator                   feb54a2624e6983617685047c717427f
meta::type::internal_function           eff3cf31e2635f51c83836f116c99d2f
meta::type::library                     7622e8d65e03066668bade74715d65ad
meta::type::message_color               557a1b44979cbf77a7251fbdc4c5b82c
meta::type::meta                        c6250056816b58a9608dd1b2614246f8
meta::type::parent                      09d1d03379e4e0b262e06939f4e00464
meta::type::retriever                   71a29050bf9f20f6c71afddff83addc9
meta::type::state                       84da7d5220471307f1f990c5057d3319
retriever::file                         3bbc9d8a887a536044bafff1d54def7e
retriever::id                           4da6080168d32445150cc4200af7af6e
retriever::object                       c7633990b4e01bdc783da7e545799f4f
retriever::perl                         f41938e6dbad317f62abffc1e4d28cca

__
meta::parent('/home/spencertipping/bin/repository', <<'__');
function::dupdate                               3203750417390913ae3892002b53bdc1
meta::type::cached_dependency                   b9dc0b20c2d3af0deb3b835b20cac4a7
parent::/home/spencertipping/bin/configuration  99a1d31e9e499afe6e49a7e9bb2787b2
retriever::http                                 a23617a5787de41d1a89ad4496cacce3

__
meta::parent('/home/spencertipping/conjectures/perl-objects/js', <<'__');
meta::type::js                           0377fcc438f3af85ec87d4770b8cd307
parent::/home/spencertipping/bin/object  7374722eec54c39ab752e3fb032c1886

__
meta::parent('/home/spencertipping/conjectures/perl-objects/sdoc', <<'__');
function::sdoc                           c681cb2a062f2073e9756779450d94bf
function::sdoc-html                      7e7de47fe059a336309a4a0c06856401
function::sdocp                          c3d738d982ba87418a298ff58478a85b
meta::type::sdoc                         22cd7315641d38c9d536344e83c36bed
meta::type::slibrary                     95474943c4a5f8ff17d3cf66ddb7c386
parent::/home/spencertipping/bin/object  7374722eec54c39ab752e3fb032c1886
retriever::html-sdoc                     2a5d5aa45e2d7576f79e045177d8705c
retriever::sdoc                          662061e9e41491e2a1debd6862ccf1e7
retriever::sdocp                         330694ea14a23bb04b65c761075cd946

__
meta::parent('compressed', <<'__');
function::compress                       70408dde290c164219dadd70f3f40524
function::uncompress                     5f7d0f3274d0fe0652ccdfa0059049fa
internal_function::compress_data         e94cf515212be7e5d01d482baaf684fb
internal_function::uncompress_data       4ffa231fa6a6eaaed192c5f0bfdfa821
meta::type::bzip2                        d0ec4034cc6e078d6968b0394330fed1
parent::/home/spencertipping/bin/object  7374722eec54c39ab752e3fb032c1886
retriever::bunzip2                       e218e119a85eca5752d9064b14ed50c3
retriever::bzip2                         a60b49e7dcd79f466f2137eafd761630

__
meta::parent('object', <<'__');
bootstrap::html                         f44dd03cb0c904b3a5f69fbda5f018d0
bootstrap::initialization               1cf74e7209f32722a79b6e49e3907fd3
bootstrap::perldoc                      5793df44bdd2526bb461272924abfd4b
function::ad                            77a05d9a6fef7871b2c3e8e94b56870a
function::alias                         8eeeeb4e064ef3aba7edf8f254427bc2
function::cat                           f684de6c8776617a437b76009114f52e
function::cc                            12ea9176e388400704d823433c209b7a
function::ccc                           d151a9793edd83f80fb880b7f0ab9b34
function::child                         f5764adf0b4e892f147a9b6b68d4816f
function::clone                         bb42e04e10a8e54e88786b6fbc4fb213
function::cp                            3fe69d1b58d90045ad520048977538c4
function::create                        3010d55f4dfa59a998742e07823ed54d
function::current-state                 6f03f86f1901e9ef07fdb5d4079a914c
function::disable                       53b449708cc2ffdefa352e53bb7d847d
function::edit                          9ce5ba1ae4607e8cf1975080bcde1cf4
function::enable                        7de1cedc36841f5de8f9fdfbc3b65097
function::export                        2374cd1dbf7616cb38cafba4e171075d
function::extern                        1290a5223e2824763eecfb3a54961eff
function::grep                          55c3cea8ff4ec2403be2a9d948e59f14
function::hash                          6ee131d093e95b80039b4df9c7c84a02
function::hook                          675cdb98b5dd8567bdd5a02ead6184b5
function::hooks                         3d989899c616f7440429a2d9bf1cc44b
function::identity                      6523885762fcc2f354fc25cf6ed126ce
function::import                        5d0f0634cbd01274f2237717507198a2
function::initial-state                 03d8ed608855a723124e79ca184d8e73
function::is                            41564c8f21b12ab80824ac825266d805
function::load-state                    b6cf278a1f351f316fa6e070359b6081
function::lock                          5d8db258704e6a8623fac796f62fac02
function::ls                            01a23d51d5b529e03943bd57e33f92df
function::mv                            4a0e338a6edb89ad1e2c779d51d4d47b
function::name                          955ba2d1fe1d67cd78651a4042283b00
function::parents                       3da9e63b5aae9e2f5dcc946a86d166aa
function::perl                          a0f341ea54391b63b6195e7992b6a686
function::rd                            eea4e1cdd9133abb985205ae5daf5f15
function::reload                        1589f4cf8374e0011991cb8907afca3e
function::rm                            6f6fd7a6c25558eb469d78ea888f8551
function::save                          778c0e1043b9c6c96fb8f266f8061624
function::save-state                    5af59ebc4ad8965767e4dc106d3b557e
function::serialize                     a19ada2d2558ea9da3a7942fb913e15f
function::serialize-single              aa77af032272f5a2664e21713739a223
function::sh                            1b2f542ca9dd63ad437058b7f6f61aac
function::shb                           7b2685a4041c25bc495816e472bdace5
function::shell                         a87f389b94713e5855e62241d649d01d
function::size                          8d4bd7a84ece556717f8ba3bf258d33c
function::snapshot                      56939a47f2758421669641e15ebd66eb
function::state                         8c68044dccae28f33244d0c7e9e9acfb
function::touch                         3991b1b7c7187566f50e5e58ce01fa06
function::unlock                        b4aac02f7f3fb700acf4acfd9b180ceb
function::update                        ac391dc90e507e7586c81850e7c2ecdd
function::update-from                   631721c4dc30e11b2023a6703cbcef52
function::usage                         5bdd370f5a56cfbf199e08d398091444
function::verify                        0c0cc1dfeab7d705919df122f7850a4f
indicator::cc                           3db7509c521ee6abfedd33d5f0148ed3
indicator::locked                       fc2b4f4ca0d6a334b9ac423d06c8f18c
indicator::path                         8a9685787cda6af8f63594f6dcde7582
internal_function::around_hook          7cc876e7c5f78c34654337fc95255587
internal_function::associate            05a75afb70daee635eefec8ae037f593
internal_function::attribute            dd6f010f9688977464783f60f5b6d3dd
internal_function::attribute_is         a145549f6ce44abbcf66308b426d30ec
internal_function::cache                eb9da45580a9ac0882baf98acd2ecd60
internal_function::chmod_self           2035e861eedab55ba0a9f6f5a068ca70
internal_function::dangerous            46c4baaa214ab3d05af43e28083d5141
internal_function::debug_trace          0faf9d9f4159d72dfe4481f6f3607ce1
internal_function::execute              f0924e087d978ff2ab1e117124db3042
internal_function::exported             3ec48f01deefa840b52111f2e3f34749
internal_function::extension_for        9de8261d69cc93e9b92072b89c89befd
internal_function::fast_hash            ee5eba48f837fda0fe472645fdd8899a
internal_function::file::read           e647752332c8e05e81646a3ff98f9a8e
internal_function::file::write          3e290fdcb353c6f842eb5a40f2e575f8
internal_function::fnv_hash             c36d56f1e13a60ae427afc43ba025afc
internal_function::hypothetically       b83e3f894a6df8623ccd370515dfd976
internal_function::internal::main       f31f2945a19a668d92505f114ab29c78
internal_function::invoke_editor_on     5eb976796f0ec172d6ec036116a2f41e
internal_function::is_locked            da12ced6aa38295251f7e748ffd22925
internal_function::namespace            784d2e96003550681a4ae02b8d6d0a27
internal_function::parent_attributes    f6ccfaa982ab1a4d066043981aaca277
internal_function::parent_ordering      57b6da88f76b59f3fed9abfa61280e5e
internal_function::retrieve             8a34d1fe047fe1b40c3d2957c4a789eb
internal_function::retrieve_with_hooks  0f1b0220ccd973d57a2e96ff00458cf2
internal_function::select_keys          a5e3532ec6d58151d0ee24416ea1e2b5
internal_function::separate_options     34ec41a6edaa15adde607a0db3ccfa36
internal_function::strip                14f490b10ebd519e829d8ae20ea4d536
internal_function::table_display        d575f4dc873b2e0be5bd7352047fd904
internal_function::temporary_name       6f548d101fc68356515ffd0fc9ae0c93
internal_function::translate_backtrace  d77a56d608473b3cd8a3c6cb84185e10
internal_function::with_exported        df345d5095d5ed13328ddd07ea922b36
library::shell                          6b9f3befb61a01e9132a440601f8ea0a
library::terminal                       7e2d045782405934a9614fe04bcfe559
message_color::cc                       2218ef0f7425de5c717762ffb100eb43
message_color::state                    03621cd6ac0b1a40d703f41e26c5807f
message_color::states                   ac66eeeff487b5f43f88a78ea18b3d56
meta::configure                         69c2e727c124521d074fde21f8bbc4db
meta::externalize                       aa44e27e0bbee6f0ca4de25d603a1fc7
meta::functor::editable                 48246c608f363de66511400e00b26164
meta::type::alias                       889d26d2df385e9ff8e2da7de4e48374
meta::type::bootstrap                   51108ab2ddb8d966e927c8f62d9ef3e5
meta::type::cache                       9267171f2eace476f64a1a670eaaf2c7
meta::type::data                        120e1649a468d3b3fd3fb783b4168499
meta::type::function                    8ea626198861dc59dd7f303eecb5ff88
meta::type::hook                        ff92aef328b6bdc6f87ddd0821f3e42f
meta::type::inc                         78e0375b6725487cb1f0deca41e96bbe
meta::type::indicator                   feb54a2624e6983617685047c717427f
meta::type::internal_function           eff3cf31e2635f51c83836f116c99d2f
meta::type::library                     7622e8d65e03066668bade74715d65ad
meta::type::message_color               557a1b44979cbf77a7251fbdc4c5b82c
meta::type::meta                        c6250056816b58a9608dd1b2614246f8
meta::type::parent                      09d1d03379e4e0b262e06939f4e00464
meta::type::retriever                   71a29050bf9f20f6c71afddff83addc9
meta::type::state                       84da7d5220471307f1f990c5057d3319
retriever::file                         3bbc9d8a887a536044bafff1d54def7e
retriever::id                           4da6080168d32445150cc4200af7af6e
retriever::object                       c7633990b4e01bdc783da7e545799f4f
retriever::perl                         f41938e6dbad317f62abffc1e4d28cca

__
meta::parent('preprocessor', <<'__');
function::preprocess           ab5526a02ff417d4c162357dc327e7c4
meta::functor::html-templates  2771200f87e9cbfeecfb5f8a0f796f18
meta::type::template           bc4b0c80b5efc716b19e99b832c22bf3
parent::object                 7374722eec54c39ab752e3fb032c1886
retriever::pp                  3b5f5c5d30c5a04f72056dedaacfe7b7
template::comment              dfe273d2dad3d8159b847545e4e5c309
template::eval                 1a0e2124a05056be4abc11803883c294
template::failing_conditional  e3a4523110dd859e828f342185de7c62
template::include              47b5552d609d97fe7f2522d5c1027014
template::pinclude             c07ff79bf8d642cceaa9ef844bfcb189
template::script-include       76be051ad116449ddebd10e7c3729afd
template::style-include        8e5a06b70e1b00379765f319bf6c8066

__
meta::retriever('bunzip2', <<'__');
# Allows you to transparently decompress stuff.
return undef unless exists $data{"bzip2::$_[0]"};
uncompress_data($data{"bzip2::$_[0]"});

__
meta::retriever('bzip2', <<'__');
# Allows you to put a bzip2:: prefix on something to specify that it should be compressed.
# This is useful when you want to retrieve plain stuff but assign into a packed attribute.

return undef unless $_[0] =~ /^bzip2::(.*)$/;
compress_data(retrieve($1));

__
meta::retriever('file', '-f $_[0] ? file::read($_[0]) : undef;');
meta::retriever('html-sdoc', <<'__');
my ($attribute) = @_;
return undef unless $attribute =~ s/^html::/sdoc::/ and exists $data{$attribute};
sdoc_html($attribute);

__
meta::retriever('http', <<'__');
use LWP::Simple ();
return undef unless $_[0] =~ /^(?:http:)?\/\/(\w+.*)$/;
LWP::Simple::get("http://$1");

__
meta::retriever('id', '$_[0] =~ /^id::/ ? substr($_[0], 4) : undef;');
meta::retriever('object', <<'__');
# Fetch a property from another Perl object. This uses the 'cat' function.
return undef unless $_[0] =~ /^object::(.*?)::(.*)$/ && -x $1 && qx|$1 is '$2'|;
join '', qx|$1 cat '$2'|;

__
meta::retriever('perl', <<'__');
# Lets you use the result of evaluating some Perl expression
return undef unless $_[0] =~ /^perl::(.*)$/;
eval $1;

__
meta::retriever('pp', <<'__');
return undef unless namespace($_[0]) eq 'pp';
my $attr = retrieve(attribute($_[0]));
defined $attr ? preprocess($attr) : undef;
__
meta::retriever('sdoc', 'exists $data{"sdoc::$_[0]"} ? sdoc("sdoc::$_[0]") : undef;');
meta::retriever('sdocp', <<'__');
my $attribute = attribute($_[0]);
exists $data{"sdoc::$attribute"} ? sdocp("sdoc::$attribute") : undef;
__
meta::sdoc('html::test', <<'__');
<!doctype html>
- html << end
  - head << end
    - script src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.js'

    - script << end
      - pinclude pp::js::dependencies
      - pinclude pp::js::modules

      var t = function () {$('body').append($('<div>').text(Array.prototype.join.call(arguments, ', ') + ' -> ' + test_case.apply(this, arguments)))};

      $(function () {
        - pinclude pp::js::test
      });
    - end

    - style << end
      body > div {font-family: monospace}
    - end
  - end
  - body << end
  - end
- end

__
meta::sdoc('js::console', <<'__');
Console-based testing.
This color-codes the test output depending on error status.

var t = function () {try       {console.log(Array.prototype.join.call(arguments, ', ') + ' \033[1;32m' + test_case.apply(this, arguments) + '\033[0;0m')}
                     catch (e) {console.log(Array.prototype.join.call(arguments, ', ') + ' \033[1;31m' + e                                + '\033[0;0m')}};

__
meta::sdoc('js::dependencies', <<'__');
Module dependencies.
Usually this is just Caterwaul and the standard extension. If you modify these, you should probably also run 'dependencies edit' to inform the script about where these files are downloaded
from.

- include caterwaul.min.js
- include caterwaul.std.min.js

__
meta::sdoc('js::modules', <<'__');

- include js::scratch

__
meta::sdoc('js::repl', <<'__');
Unit tests.
These are run automatically prior to starting the REPL.

- pinclude pp::js::test-setup

REPL driver.
This enters the node.js REPL and lets you experiment with your extension.

require('repl').start('caterwaul> ').context.caterwaul = caterwaul;

__
meta::sdoc('js::scratch', <<'__');
caterwaul.js_all()(function ($) {

  console.log('scratchpad code goes here (run "scratch" to edit)')})(caterwaul);

__
meta::sdoc('js::test', <<'__');
Unit tests.
These are quick, visible assertions to make sure that the setup works properly. The test_case function is called automatically by t(), which is customized to work on whatever platform you're
running under (e.g. node.js or a browser).

test_case = function (x) {return caterwaul.parse(x).structure()};

__
meta::sdoc('js::test-setup', <<'__');
Prerequisites.
We need to load dependencies and the extension modules.

- pinclude pp::js::dependencies
- pinclude pp::js::modules

Unit tests.
These are loaded automatically each time you boot up the REPL. This makes it easy to see when something has gone wrong.

- pinclude pp::js::console
- pinclude pp::js::test

__
meta::template('comment', '\'\';     # A mechanism for line or block comments.');
meta::template('eval', <<'__');
my $result = eval $_[0];
terminal::warning("Error during template evaluation: $@") if $@;
$result;
__
meta::template('failing_conditional', <<'__');
my ($commands)    = @_;
my $should_return = $commands =~ / if (.*)$/ && ! eval $1;
terminal::warning("eval of template condition failed: $@") if $@;
$should_return;
__
meta::template('include', <<'__');
my ($commands) = @_;
return '' if template::failing_conditional($commands);
join "\n", map retrieve($_), split /\s+/, $commands;
__
meta::template('pinclude', <<'__');
# Just like the regular include, but makes sure to insert paragraph boundaries
# (this is required for SDoc to function properly).

my ($commands) = @_;
return '' if template::failing_conditional($commands);
my $text = join "\n\n", map retrieve($_), split /\s+/, $commands;
"\n\n$text\n\n";
__
meta::template('script-include', <<'__');
my ($name) = @_;
my $s      = 'script';
my $script = retrieve($name);
"<$s>\n$script\n</$s>";

__
meta::template('style-include', <<'__');
my ($name) = @_;
my $s      = 'style';
my $style  = retrieve($name);
"<$s>\n$style\n</$s>";

__
internal::main();

__END__